#!/bin/bash

# cpu av8 av7 x86 x64
# NDK + +  .   .   .  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc

lib='ffmpeg'
dsc='FFmpeg is the leading multimedia framework'
lic='GLP-2.0'
vrs='n6.2-dev^{}'
src='https://github.com/FFmpeg/FFmpeg.git'
cfg='ac'
eta='777'
mki='install'
make_install='install'
pkg='libavcodec'

ac_nohost=true


lst_inc=''
lst_lib=''
lst_bin=''

ffblock="FFDATA"

applyOptions(){
    IFS='|' read -r -a keys <<<"$1"
    for k in "${keys[@]}"; do
        IFS=',' read -r -a field <<<"$k"
        dep+=(${field[0]/;/ })
        opt+=(${field[1]/;/ })
    done
}

zenSplit(){
    IFS='|' read -r -a keys <<<"$1"
    echo "${keys[@]}"
}

zenTagList(){
    tagList=$(git ls-remote $src | grep 'refs/tags/' | sed 's/^.*refs\/tags\///g')
    echo "$tagList" | grep '^n' | tail -n 6 | sed -z 's/\n/|/g'
}

selectExtras(){
    local tag=$1
    local block=$(awk '/^<<.'"$ffblock"'./{flag=1; next} /^'"$ffblock"'/{flag=0} flag' $0 | grep -P "\t${tag}\t" | sed 's/\t/\n/g')
    local cfgzen=()
    while IFS=$'\n' read -r -a entry; do
        cfgzen+=( "${entry}" );
    done <<<"${block}"
    local test_zen=$(IFS=$'\n' zenity --list --checklist --text="Features" \
        --print-column=4 --hide-column=4 --height=600 --width=800 \
        --column "Use" --column "lib" --column "type" --column "ffopt"  --column "Description" \
        "${cfgzen[@]}")
    IFS='|' read -r -a keys <<<"$test_zen"
    for k in "${keys[@]}"; do
        IFS=';' read -r -a field <<<"$k"
        dep+=(${field[0]/\'/})
        opt+=(${field[1]/\'/})
    done
    #echo "deps: ${dep[@]}"
    #echo "opts: ${opt[@]}"
}

ffmpegConfig(){

    test "$TERM_PROGRAM" == "vscode" && \
        printf "\nThis won't run on VSCODE.\nExiting...\n\n" && \
        exit 0
        
    archOpts=(
        TRUE    NATIVE          "native"
        false   android-arm64   "aa8"
        false   android-armv7   "aa7"
        false   android-x64     "aa64"
        false   linux-arm64     "la8"
        false   linux-armv7     "la7"
        false   linux-x64       "la7"
        false   windows-arm64   "wa8"
        false   windows-x64     "wx64"
    )

    sizeOpts=(
        TRUE    Performance     ","
        false   Size            ",--enable-small;--disable-debug"
    )

    zen=$(zenity --width=500 --forms --title "Build Options" \
        --add-combo "Target Arch" --combo-values "native|android-armv8|android-armv7|android-x64|linux-arm64|linux-x64|windows-arm64|windows-x64" \
        --add-combo "Source Version" --combo-values "$(zenTagList)" \
        --add-combo "Link Type" --combo-values "static|shared|both" \
        --add-combo "Build Executables" --combo-values "yes|no" \
        --add-combo "Optimize for" --combo-values "Size|Performance" \
        --add-combo "Audio External Libs" --combo-values "none|basic|extended" \
        --add-combo "Video External Libs" --combo-values "none|basic|extended" \
        --add-combo "Net External Libs" --combo-values "none|basic|extended" \
        --add-combo "Subtitle External Libs" --combo-values "none|basic|extended" \
        --add-combo "I/O External Libs" --combo-values "none|basic|extended" \
        --add-entry "Version Name" \
    )

    #0 android-armv8
    #1 n6.2-dev^{}
    #2 static yes Performance basic basic none none 6.2-basicAV
    extopts=
    mainOpts=( $(zenSplit ${zen[@]}) )
    zfilter=()
    dep=
    opt=

    argList=( "${mainOpts[0]}" )
    bra=${mainOpts[1]}

    test "x${mainOpts[2]}" != "xshared" && argList+=( "--static" )
    test "x${mainOpts[2]}" != "xstatic" && argList+=( "--shared" )
    test "x${mainOpts[3]}" != "xno" && argList+=( "--bin" )
    test "x${mainOpts[4]}" != "xPerformance" && extopts="--enable-small"
    test "x${mainOpts[5]}" != "xnone" && zfilter+=( "audio" )
    test "x${mainOpts[6]}" != "xnone" && zfilter+=( "video" )
    test "x${mainOpts[7]}" != "xnone" && zfilter+=( "net" )
    test "x${mainOpts[8]}" != "xnone" && zfilter+=( "sub" )
    test "x${mainOpts[9]}" != "xnone" && zfilter+=( "io" )
    extraversion="${mainOpts[10]}"

    selectExtras $(IFS=$'|'; printf %s "${zfilter[*]}")
    argList+=( "--force" )
    #echo "arguments: ${argList[@]}"
    #echo "ffmpeg options: ${opt[@]}"
    #echo "lib dependencies: ${dep[@]}"
    dep=$(echo "${dep[@]}")
    extlibs=$(echo "${opt[@]}")
	cat <<-EOF >$(pwd)/ffmpeg-${extraversion}.cfg
		#!/bin/bash

		dep='${dep}'
		argList=( ${argList[@]} )
		extlibs='${extlibs}'
        extraversion='${extraversion}'
		EOF

    set -- "${argList[@]}"
}

loadConfig(){
    echo "loading $1"
    if [ -f "$1" ]; then
        source $1
        echo "arguments: ${argList[@]}"
        echo "ffmpeg options: ${extlibs}"
        echo "lib dependencies: ${dep}"
        echo "version: ${extraversion}"
    fi
    set -- "${argList[@]}"
}


extraOpts(){
    case $1 in
        --patch-vvc) applyVvcPatch=true;;
        --enable-*)  extlibs+=" $1"; addDep $1;;
        --disable-*) extlibs+=" $1";;
    esac
    return 0
}

case $1 in
    --config)   ffmpegConfig;;
    --load)     shift; loadConfig $1;;
esac

source xbuild

extopts="--pkg-config-flags=--static \
         --enable-lto \
         --enable-runtime-cpudetect \
         --disable-symver \
         --cross-prefix=${CROSS_PREFIX} \
         --extra-version=$extraversion $extopts"

nonfree=false
gpl=false
v3=false

for d in $dep; do
     case $d in
        fdk-aac|openssl) nonfree=true;;
        frei0r|vidstab|x264|x265|xavs|xvidcore) gpl=true;;
        opencore-amr) v3=true;;
        vvenc) applyVvcPatch=true;;
     esac
done

$nonfree && extlibs+=' --enable-nonfree'
$gpl && extlibs+=' --enable-gpl'
$v3 && extlibs+=' --enable-version3'

if $build_shared; then
     extlibs+=" --enable-shared --disable-static"
fi
CSH=

$host_arm && extopts+=' --enable-neon'
$host_x86 && extopts+=' --disable-asm'

case $host_os in
    android)    CPPFLAGS+=" -Ofast -fPIC -fPIE -fblocks -Wno-implicit-const-int-float-conversion -Wno-deprecated-declarations" # -ffunction-sections -fdata-sections -Wl,--gc-sections"
                extopts+=" --enable-jni --enable-mediacodec --enable-asm --enable-inline-asm --enable-pic --enable-cross-compile" #unecessary --disable-alsa --disable-indev=android_camera 
                extopts+=" --enable-vulkan --extra-cflags=-I${ANDROID_NDK_HOME}/sources/third_party/vulkan/src/include/vulkan --extra-ldflags=-lcamera2ndk,-lmediandk,-lnativewindow"
                LDFLAGS+=" -lcamera2ndk -lmediandk -lnativewindow"
                ;;
     gnu)       extopts+=" --enable-opencl --enable-opengl --enable-pic" LDFLAGS+=" -ldl -lstdc++"
                lspci -k | grep -A 2 -i "VGA" | grep amd && extopts+=" --enable-nvenc"
                lspci -k | grep -A 2 -i "VGA" | grep nvidia && extopts+=" --enable-nvenc"
                ;;
esac

ac_config="--arch=$CPU \
     --target-os=${PLATFORM,,} \
     --cc=$CC \
     --ar=$AR \
     --strip=$STRIP \
     --disable-doc \
     --disable-htmlpages \
     --disable-ffplay \
     --pkg-config=$(which pkg-config) \
     --extra-libs=-lpthread \
     $extopts \
     $extlibs"
# make the log cleaner

applyPatch(){
    if [ ! -f "${dir_src}/vvc_patched" ]; then
        pushd ${dir_src}
        wget -O Add-support-for-H266-VVC.patch https://patchwork.ffmpeg.org/series/9992/mbox/
        git apply --check Add-support-for-H266-VVC.patch || git apply Add-support-for-H266-VVC.patch --exclude=libavcodec/version.h
        touch vvc_patched
        popd
    fi
}

before_build(){
    test ${applyVvcPatch} && applyPatch
}

NPROC=16

start



<<'FFDATA'
FALSE	aom	video	'aom;--enable-libaom'	'Alliance for Open Media AV1 codec'
FALSE	aribb24	video	'aribb24;--enable-libaribb24'	'A library for ARIB STD-B24, decoding JIS 8 bit characters and parsing MPEG-TS stream'
FALSE	avisynth	video	'avisynth;--enable-avisynth'	'A powerful nonlinear scripting language for video'
FALSE	celt	audio	'celt;--enable-libcelt'	'CELT is a low-delay audio codec'
FALSE	chromaprint	audio	'chromaprint;--enable-chromaprint'	'C library for generating audio fingerprints used by AcoustID'
FALSE	codec2	audio	'codec2;--enable-libcodec2'	'A speech codec for 2400 bit/s and below'
FALSE	dav1d	video	'dav1d;--enable-libdav1d'	'AV1 cross-platform decoder, open-source, and focused on speed and correctness.'
FALSE	davs2	video	'davs2;--enable-libdavs2'	'An open-source decoder of AVS2-P2/IEEE1857.4 video coding standard'
FALSE	fdk-aac	audio	'fdk-aac;--enable-libfdk-aac'	'A standalone library of the Fraunhofer FDK AAC code from Android'
FALSE	flite	audio	'flite;--enable-libflite'	'A small fast portable speech synthesis system'
FALSE	fontconfig	sub	'fontconfig;--enable-libfontconfig'	'Font customization and configuration library'
FALSE	freetype	sub	'freetype;--enable-libfreetype'	'A free, high-quality, and portable font engine.'
FALSE	frei0r	video	'frei0r;--enable-frei0r'	'A large collection of free and portable video plugins'
FALSE	fribidi	sub	'fribidi;--enable-libfribidi'	'Unicode Bidirectional Algorithm Library'
FALSE	glslang	video	'glslang;--enable-libglslang'	'OpenGL and OpenGL ES shader front end and validator'
FALSE	gmp	net	'gmp;--enable-gmp'	'GNU Multiple Precision Arithmetic Library'
FALSE	gnutls	net	'gnutls;--enable-gnutls'	'GnuTLS implements the TLS/SSL (Transport Layer Security aka Secure Sockets Layer) protocol'
FALSE	harfbuzz	sub	'harfbuzz;--enable-libharfbuzz'	'HarfBuzz text shaping engine'
FALSE	kvazaar	video	'kvazaar;--enable-libkvazaar'	'An open source C library for efficient image processing and image analysis operations'
FALSE	ladspa	audio	'ladspa;--enable-ladspa'	'Linux Audio Developers Simple Plugin API'
FALSE	lame	audio	'lame;--enable-libmp3lame'	'LAME is a high quality MPEG Audio Layer III (MP3) encoder'
FALSE	lcms2	video	'lcms2;--enable-lcms2'	'A free, open source, CMM engine. It provides fast transforms between ICC profiles'
FALSE	lensfun	video	'lensfun;--enable-liblensfun'	'An open source database of photographic lenses and their characteristics'
FALSE	libass	sub	'libass;--enable-libass'	'LibASS is an SSA/ASS subtitles rendering library'
FALSE	libbluray	io	'libbluray;--enable-libbluray'	'Library to access Blu-Ray disks'
FALSE	libbs2b	audio	'libbs2b;--enable-libbs2b'	'Bauer stereophonic-to-binaural DSP'
FALSE	libcaca	sub	'libcaca;--enable-libcaca'	'Colour AsCii Art library'
FALSE	libcdio	io	'libcdio;--enable-libcdio'	'Portable CD-ROM I/O library'
FALSE	libdc1394	io	'libdc1394;--enable-libdc1394'	'IIDC Camera Control Library '
FALSE	libgcrypt	net	'libgcrypt;--enable-gcrypt'	'The GNU crypto library'
FALSE	libgme	audio	'libgme;--enable-libgme'	'Blarggs video game music emulation library'
FALSE	libgsm	audio	'libgsm;--enable-libgsm'	'GSM 06.10 lossy speech compression'
FALSE	libiec61883	io	'libiec61883;--enable-libiec61883'	'An isochronous streaming media library for IEEE 1394'
FALSE	libilbc	net	'libilbc;--enable-libilbc'	'Internet Low Bitrate Codec (iLBC) library'
FALSE	libjack	audio	'libjack;--enable-libjack'	'Jack Audio Connection Kit: a low-latency synchronous callback-based media server'
FALSE	libjxl	video	'libjxl;--enable-libjxl'	'A fast, compressed, persistent binary data store library for C.'
FALSE	libklvanc	?	'libklvanc;--enable-libklvanc'	'VANC Processing Framework'
FALSE	libmodplug	audio	'libmodplug;--enable-libmodplug'	'The ModPlug mod file playing library.'
FALSE	libmysofa	extra	'libmysofa;--enable-libmysofa'	'Reader for AES SOFA files to get better HRTFs'
FALSE	libplacebo	video	'libplacebo;--enable-libplacebo'	'Reusable library for GPU-accelerated image/video processing primitives and shaders'
FALSE	libpulse	audio	'libpulse;--enable-libpulse'	'PulseAudio Client Interface'
FALSE	librist	net	'librist;--enable-librist'	'A library that can be used to easily add the RIST protocol to your application.'
FALSE	librsvg	video	'librsvg;--enable-librsvg'	'A small library to render Scalable Vector Graphics (SVG)'
FALSE	librtmp	net	'librtmp;--enable-librtmp'	'rtmpdump is a toolkit for RTMP streams. All forms of RTMP are supported, including rtmp://, rtmpt://, rtmpe://, rtmpte://, and rtmps://.'
FALSE	librubberband	audio	'librubberband;--enable-librubberband'	'An audio time-stretching and pitch-shifting library and utility program.'
FALSE	libshaderc	video	'libshaderc;--enable-libshaderc'	'A library for compiling shader strings into SPIR-V.'
FALSE	libsrt	net	'libsrt;--enable-libsrt'	'Secure Reliable Transport (SRT) is an open source transport technology that optimizes streaming performance across unpredictable networks, such as the Internet.'
FALSE	libssh	net	'libssh;--enable-libssh'	'The SSH library'
FALSE	libwebp	video	'libwebp;--enable-libwebp'	'Library to encode and decode images in WebP format'
FALSE	libxml2	extra	'libxml2;--enable-libxml2'	'GNOME XML library'
FALSE	libzmq	net	'libzmq;--enable-libzmq'	'ZeroMQ core engine in C++, implements ZMTP/3.1'
FALSE	lv2	audio	'lv2;--enable-lv2'	'An extensible audio plugin interface'
FALSE	mbedtls	net	'mbedtls;--enable-mbedtls'	'An open source, portable, easy to use, readable and flexible SSL library.'
FALSE	openal	audio	'openal;--enable-openal'	'OpenAL Soft with Android support'
FALSE	opencl	video	'opencl;--enable-opencl'	'Khronos OpenCL-Headers'
FALSE	opencore-amr	audio	'opencore-amr;--enable-libopencore-amrnb --enable-libopencore-amrwb'	'OpenCORE Adaptive Multi Rate (AMR) speech codec'
FALSE	opencv	video	'opencv;--enable-libopencv'	'Open Source Computer Vision Library'
FALSE	openh264	video	'openh264;--enable-libopenh264'	'Open Source H.264 Codec'
FALSE	openjpeg	video	'openjpeg;--enable-libopenjpeg'	'OpenJPEG is an open-source JPEG 2000 codec written in C language.'
FALSE	openmpt	audio	'openmpt;--enable-libopenmpt'	'a library to render tracker music'
FALSE	openssl	net	'openssl;--enable-openssl'	'TLS/SSL and crypto library'
FALSE	opus	audio	'opus;--enable-libopus'	'Opus is a codec for interactive speech and audio transmission over the Internet'
FALSE	pocketsphinx	audio	'pocketsphinx;--enable-pocketsphinx'	'Speech recognition tool'
FALSE	shine	audio	'shine;--enable-libshine'	'Super fast fixed-point MP3 encoder.'
FALSE	snappy	audio	'snappy;--enable-libsnappy'	'Snappy is a compression/decompression library'
FALSE	soxr	audio	'soxr;--enable-libsoxr'	'The SoX resampler library'
FALSE	speex	audio	'speex;--enable-libspeex'	'Speex is an audio codec tuned for speech'
FALSE	svtav1	video	'svtav1;--enable-libsvtav1'	'Scalable Video Technology for AV1 (SVT-AV1 Encoder and Decoder)'
FALSE	tensorflow	extra	'tensorflow;--enable-libtensorflow'	'An Open Source Machine Learning Framework for Everyone'
FALSE	tesseract	sub	'tesseract;--enable-libtesseract'	'An OCR Engine that was developed at HP Labs between 1985 and 1995... and now at Google'
FALSE	theora	video	'theora;--enable-libtheora'	'Theora video compression format'
FALSE	twolame	audio	'twolame;--enable-libtwolame'	'MPEG Audio Layer 2 (MP2) encoder'
FALSE	uavs3d	audio	'uavs3d;--enable-libuavs3d'	'AVS3 decoder which supports AVS3-P2 baseline profile.'
FALSE	vapoursynth	video	'vapoursynth;--enable-vapoursynth'	'A video processing framework with simplicity in mind'
FALSE	vidstab	video	'vidstab;--enable-libvidstab'	'Vidstab is a video stabilization library which can be plugged-in with Ffmpeg and Transcode'
FALSE	vmaf	video	'vmaf;--enable-libvmaf'	'Perceptual video quality assessment based on multi-method fusion'
FALSE	vo-amrwbenc	audio	'vo-amrwbenc;--enable-libvo-amrwbenc'	'VisualOn Adaptive Multi-Rate Wideband speech codec library'
FALSE	vorbis	audio	'vorbis;--enable-libvorbis'	'Ogg Vorbis audio format'
FALSE	vpx	video	'vpx;--enable-libvpx'	'WebM Project VPx codec implementation'
FALSE	vulkan	video	'vulkan;--enable-vulkan'	'Khronos Vulkan-Headers'
FALSE	vvdec	video	'vvdec;--enable-libvvdec'	'Fraunhofer Versatile Video Decoder (VVdeC)'
FALSE	vvenc	video	'vvenc;--enable-libvvenc'	'Fraunhofer Versatile Video Encoder'
FALSE	x264	video	'x264;--enable-libx264'	'x264, the best and fastest H.264 encoder'
FALSE	x265	video	'x265;--enable-libx265'	'x265 is an open source HEVC encoder'
FALSE	xavs2	video	'xavs2;--enable-libxavs2'	'An open-source encoder of AVS2-P2/IEEE1857.4 video coding standard'
FALSE	xavs	video	'xavs;--enable-libxavs'	'High quality encoder and decoder of the Audio Video Standard of China (AVS)'
FALSE	xvidcore	video	'xvidcore;--enable-libxvid'	'Xvid decoder/encoder library'
FALSE	zimg	video	'zimg;--enable-libzimg'	'Scaling, colorspace conversion, and dithering library'
FALSE	zvbi	io	'zvbi;--enable-libzvbi'	'VBI Capturing and Decoding Library'
FFDATA