#!/bin/bash
# 2024 diasgc

# cpu av8 av7 x86 x64
# NDK + +  .   .   .  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc

lib='ffmpeg'
dsc='FFmpeg is the leading multimedia framework'
lic='GLP-2.0'
pkg='libavcodec'
vrs='n7.1-dev^{}'
vrs_tag="${vrs/\^\{\}/}"
src='https://github.com/FFmpeg/FFmpeg.git'
src_dev='https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2'
src_tgz="https://github.com/FFmpeg/FFmpeg/archive/refs/tags/${vrs_tag}.tar.gz"
patch_skip=true

cfg='ac'
am_nohost=true


lst_inc=''
lst_lib=''
lst_bin=''
eta='777'

extractConfigList(){
	cat ${dir_src}/configure | sed -n '/'$1'=\"/,/\"/p' | sed '1d;$d;s/^ *//g'
}

zen_config(){

  test "$TERM_PROGRAM" == "vscode" && \
    printf "\nThis won't run on VSCODE terminal.\nExiting...\n\n" && \
    exit 0
  
  local git_tags=$(git ls-remote $src | grep 'refs/tags/' | sed 's/^.*refs\/tags\///g')
	git_tags=$(echo "$git_tags" | grep '^n' | tail -n 15 | sed '1!G;h;$!d' | sed -z 's/\n/|/g' | sed 's/|$//')
	git_tags="master|$git_tags"
  
  local zen=$(zenity --width=500 --forms --title "Build Options" \
    --add-combo "Target Arch" --combo-values "native|android-armv8|android-armv7|android-x64|linux-arm64|linux-x64|windows-arm64|windows-x64" \
    --add-combo "Source Version" --combo-values "${git_tags}" \
    --add-combo "Link Type" --combo-values "static|shared" \
    --add-combo "Build Executables" --combo-values "yes|no" \
    --add-combo "Optimize for" --combo-values "Size|Performance" \
    --add-combo "External Libs" --combo-values "custom|full|extended|basic|min|none" \
    --add-entry "Version Name" \
  )
  #echo "$zen"
  local zen_opts
  local xb_args
  local ff_args
  local ff_extralibs
  IFS='|' read -r -a zen_opts <<<"${zen}"

	xb_args=( "${zen_opts[0]}" )
	bra="${zen_opts[1]}"
  xb_args+=( "--${zen_opts}" )
	
  test "x${zen_opts[3]}" != "xno" && ff_args+=( "--bin" )
	test "x${zen_opts[4]}" != "xPerformance" && ff_args="--enable-small"
  
  case "{zen_opts[5]}" in
    custom)   ;;
    full)     ;;
    extended) ;;
    basic)    ;;
    min)      ;;
  esac

	test "x${zen_opts[5]}" != "xnone" && zfilter+=( "audio" )
	ff_extraversion="${zen_opts[6]}"

	selectExtras $(IFS=$'|'; printf %s "${zfilter[*]}")
	argList+=( "--force" )
}

zen_config