#!/bin/bash
# fail to build plugins
# Aa8 Aa7 A86 A64 L64 W64 La8 La7 Wa8 W86 L86
#  F   .   .   .   .   .   .   .   .   .   .  static
#  F   .   .   .   .   .   .   .   .   .   .  shared
#  F   .   .   .   .   .   .   .   .   .   .  bin

lib='ladspa'
apt='ladspa-sdk'
dsc='Linux Audio Developers Simple Plugin API'
lic='LGPL'
vrs='1.17'
src="http://www.ladspa.org/download/ladspa_sdk_${vrs}.tgz"
cfg='cmake'
dep='sndfile'
eta='60'
pc_llib='-lladspa'
cmake_static='BUILD_STATIC_LIBS'
build_strip=false

. xbuilder.sh

start

#patch 01 create CMakeLists.txt with dual static(?) shared build support

<<'XB64_PATCH'
LS0tIENNYWtlTGlzdHMudHh0CTE5NzAtMDEtMDEgMDE6MDA6MDAuMDAwMDAwMDAwICswMTAwCisrKyBDTWFrZUxpc3
RzLnR4dAkyMDIyLTAyLTAyIDIwOjIxOjE4LjIxODQ0MTgyMiArMDAwMApAQCAtMCwwICsxLDY1IEBACitjbWFrZV9t
aW5pbXVtX3JlcXVpcmVkKFZFUlNJT04gMy4yMSkKKworcHJvamVjdChsYWRzcGEKKyAgICAgICAgREVTQ1JJUFRJT0
4gIkxpbnV4IEF1ZGlvIERldmVsb3BlcnMgU2ltcGxlIFBsdWdpbiBBUEkiCisgICAgICAgIEhPTUVQQUdFX1VSTCAi
aHR0cDovL3d3dy5sYWRzcGEub3JnIgorICAgICAgICBWRVJTSU9OIDEuMTcuMCkgIyBLZWVwIGluIHN5bmMgd2l0aC
BMZXJjX2NfYXBpLmgKKworCisjIE1ha2UgYW4gb3B0aW9uLCBkZWZhdWx0aW5nIHRvIHNoYXJlZCBsaWJzLCBidXQg
YWxsb3cgLURCVUlMRF9TSEFSRURfTElCUz1PRkYKK29wdGlvbiAoQlVJTERfUExVR0lOUyAiQnVpbGQgcGx1Z2lucy
IgT04pCitvcHRpb24gKEJVSUxEX1BST0dSQU1TICJCdWlsZCBwcm9ncmFtcyIgT04pCisKK2ZpbmRfbGlicmFyeShM
SUJfU05ERklMRSBzbmRmaWxlKQoraWYoTk9UIExJQl9TTkRGSUxFKQorICAgIG1lc3NhZ2UoRkFUQUxfRVJST1IgIk
xpYiBzbmRmaWxlIG5vdCBmb3VuZCwgYWJvcnRpbmciKQorZW5kaWYoKQorZmluZF9wYXRoKEhEUl9TTkRGSUxFIHNu
ZGZpbGUuaCkKK21lc3NhZ2UoIkxJQl9TTkRGSUxFIGZvdW5kICR7TElCX1NOREZJTEV9IikKK21lc3NhZ2UoIkhlYW
RlciBpcyAke0hEUl9TTkRGSUxFfSIpCisKK2luY2x1ZGVfZGlyZWN0b3JpZXMoJHtDTUFLRV9TT1VSQ0VfRElSfS9z
cmMgJHtIRFJfU05ERklMRX0pCisKK2lmKEJVSUxEX1BMVUdJTlMpCisgICAgYWRkX2NvbXBpbGVfb3B0aW9ucygtTz
MKKyAgICAgICAgLWZsdG8KKyAgICAgICAgLWZ2aXNpYmlsaXR5PWhpZGRlbgorICAgICAgICAtZnZpc2liaWxpdHkt
aW5saW5lcy1oaWRkZW4pCisgICAgZm9yZWFjaChwbHVnaW4gYW1wIGRlbGF5IGZpbHRlciBub2lzZSBzaW5lKQorIC
AgICAgICBpZigke3BsdWdpbn0gU1RSRVFVQUwgc2luZSkKKyAgICAgICAgICAgIHNldChzcmNfZXh0IGNwcCkKKyAg
ICAgICAgZWxzZSgpCisgICAgICAgICAgICBzZXQoc3JjX2V4dCBjKQorICAgICAgICBlbmRpZigpCisgICAgICAgIG
FkZF9saWJyYXJ5KCR7cGx1Z2lufSBzcmMvcGx1Z2lucy8ke3BsdWdpbn0uJHtzcmNfZXh0fSBzcmMvbGFkc3BhLmgg
c3JjL2djY19leHBvcnRzLm1hcCkgCisgICAgICAgIHNldF90YXJnZXRfcHJvcGVydGllcygke3BsdWdpbn0gUFJPUE
VSVElFUyBPVVRQVVRfTkFNRSAke3BsdWdpbn0pCisgICAgICAgIHRhcmdldF9saW5rX2xpYnJhcmllcygke3BsdWdp
bn0gUFJJVkFURSBkbCBtICR7TElCX1NOREZJTEV9KQorICAgICAgICBsaXN0KEFQUEVORCB0YXJnZXRfcGx1Z2lucy
Ake3BsdWdpbn0pCisgICAgICAgIGlmKEJVSUxEX1NUQVRJQ19MSUJTIEFORCBCVUlMRF9TSEFSRURfTElCUykKKyAg
ICAgICAgICAgIGFkZF9saWJyYXJ5KCR7cGx1Z2lufS1zdGF0aWMgU1RBVElDIHNyYy9wbHVnaW5zLyR7cGx1Z2lufS
4ke3NyY19leHR9IHNyYy9sYWRzcGEuaCBzcmMvZ2NjX2V4cG9ydHMubWFwKQorICAgICAgICAgICAgc2V0X3Rhcmdl
dF9wcm9wZXJ0aWVzKCR7cGx1Z2lufS1zdGF0aWMgUFJPUEVSVElFUyBPVVRQVVRfTkFNRSAke3BsdWdpbn0pCisgIC
AgICAgICAgICB0YXJnZXRfbGlua19saWJyYXJpZXMoJHtwbHVnaW59LXN0YXRpYyBQUklWQVRFIGRsIG0gJHtMSUJf
U05ERklMRX0pCisgICAgICAgICAgICBsaXN0KEFQUEVORCB0YXJnZXRfcGx1Z2lucyAke3BsdWdpbn0tc3RhdGljKQ
orICAgICAgICBlbmRpZigpCisgICAgZW5kZm9yZWFjaCgpCisKKyAgICBpbnN0YWxsKAorICAgICAgICBUQVJHRVRT
ICR7dGFyZ2V0X3BsdWdpbnN9CisgICAgICAgIExJQlJBUlkgREVTVElOQVRJT04gbGlicy9sYWRzcGFfcGx1Z2lucw
orICAgICAgICBSVU5USU1FIERFU1RJTkFUSU9OIGJpbgorICAgICAgICBBUkNISVZFIERFU1RJTkFUSU9OIGxpYnMv
bGFkc3BhX3BsdWdpbnMpCitlbmRpZigpCisKK2lmKEJVSUxEX1BST0dSQU1TKQorICAgIGFkZF9leGVjdXRhYmxlKG
FuYWx5c2VwbHVnaW4gc3JjL2FuYWx5c2VwbHVnaW4uYyBzcmMvbG9hZC5jIHNyYy9kZWZhdWx0LmMpCisgICAgdGFy
Z2V0X2xpbmtfbGlicmFyaWVzKGFuYWx5c2VwbHVnaW4gZGwgbSBzbmRmaWxlKQorICAgIGFkZF9leGVjdXRhYmxlKG
FwcGx5cGx1Z2luIHNyYy9hcHBseXBsdWdpbi5jIHNyYy9sb2FkLmMgc3JjL2RlZmF1bHQuYykKKyAgICB0YXJnZXRf
bGlua19saWJyYXJpZXMoYXBwbHlwbHVnaW4gZGwgbSBzbmRmaWxlKQorICAgIGFkZF9leGVjdXRhYmxlKGxpc3RwbH
VnaW5zIHNyYy9saXN0cGx1Z2lucy5jIHNyYy9zZWFyY2guYykKKyAgICB0YXJnZXRfbGlua19saWJyYXJpZXMobGlz
dHBsdWdpbnMgZGwgbSBzbmRmaWxlKQorICAgIGluc3RhbGwoVEFSR0VUUyBhbmFseXNlcGx1Z2luIGFwcGx5cGx1Z2
luIGxpc3RwbHVnaW5zIFJVTlRJTUUgREVTVElOQVRJT04gYmluKQorZW5kaWYoKQorIyBDb25maWd1cmUgYW5kIGlu
c3RhbGwgcGtnY29uZmlnIGZpbGUKKyNjb25maWd1cmVfZmlsZShMZXJjLnBjLmluICR7Q01BS0VfQ1VSUkVOVF9CSU
5BUllfRElSfS9MZXJjLnBjIEBPTkxZKQoraW5zdGFsbChGSUxFUyBzcmMvbGFkc3BhLmggREVTVElOQVRJT04gaW5j
bHVkZSkKKwo=
XB64_PATCH



# Filelist
# --------
# libs/ladspa_plugins/libamp.a
# libs/ladspa_plugins/libdelay.a
# libs/ladspa_plugins/libamp.so
# libs/ladspa_plugins/libsine.a
# libs/ladspa_plugins/libsine.so
# libs/ladspa_plugins/libfilter.so
# libs/ladspa_plugins/libnoise.so
# libs/ladspa_plugins/libdelay.so
# libs/ladspa_plugins/libnoise.a
# libs/ladspa_plugins/libfilter.a
# include/ladspa.h
# lib/pkgconfig/ladspa.pc
# bin/listplugins
# bin/applyplugin
# bin/analyseplugin
