#!/bin/bash

lib='librsync'
dsc='Remote delta-compression library'
lic='LGPL-2.1'
src='https://github.com/librsync/librsync.git'
url='librsync.sourcefrog.net'
cfg='cmake'
dep='zlib libb2 bzip2'
eta='0'

cmake_static='BUILD_STATIC_LIBS'
cmake_config='-DINSTALL_MANFILES=OFF'

dev_vrs='2.3.3'

lst_inc='librsync.h librsync_export.h'
lst_lib='librsync'
lst_bin=''
lst_lic='COPYING AUTHORS README.md'
lst_pc='librsync.pc'

. xbuild

start

# patch 01 on CMakeLists.txt to support dual static/shared build, opt to man install and
# pkgconfig file
# patch 02 on librsync.pc.in to create pkgconfig file
<<'LZS_PATCH'
LQgEGEFkEMGsFMAyBLAzgF1QOnQD3QJABMADEUcCQMzACMtoRVAXLQKzNFtYDsALAA4mVHiRKgA1GLEAoCfIgwEKDN
jyFS5SjXqMWbWsz4A2LFRJCqIsZOkkZAAQehgfegBo3kt7U/HQTjKgwcGoAE4AxgD0AG7wYajIAPYAdlgRQSGg4dEA
7gAWSQA28OmZIQAkAN4ARkVw8EQA+gDKAErgLQC+AJQywP3QACZDTUXINWHQYQCeABQJMykRoNWLy02IAJIAQq0d3X
0SAGYArsvoySlzw6PjNdnHuKBFKbBHt2MTU7MLqEsRaqoJ5dVZVV6wUFrf4bbZ7dqdXpBADEoAAKgB5AAiGOYoAAoi
loHV4KB0Pk0KACvAUqAAOI0+LQdDwfG4AAOSTC6AAEvBhvEqVzYKhQABbLmk3LIIbwIozLAo0DIZZFU6yuYMlJMlls
zncvkCsJ9UCogDmjKmLKa8A5XPQTXy/NlYT+ANAOwAgi18U0AHKeyD4l7fGEZU1ZAkADQAChi2mimgAxLaIX0BoNgq
CegDSvpaGIAqh1fVitm0ulEclF7usIja7dysPk+sB0NMLQ7xm8vpNpsh4Kg3cswXUGs04Yc5O2wp2vj3a/3B8PAVVg
bgobV6ggJ7sp6AlRj2ZdUtAivKQ29QAAve6gaApIagGrX5DsojK45K4CgCJJMXsmEg6JKkyqijSxIlEM373o+IZ9mE
A6itMpLHEk5zQZ+oBzPiAY7GmTTgBikAxm0+ItC0WwYn6JrBMgxzYQAWnCyZFn6WKgJ67EeoxWwxs0SZsVirZZDOc7
drAvY/EhK5gsxuybLsbSem0WzkZuOy8fxik7MpqnqUcokdvAXYqpJi6IcudZAiCcksXCelqd0YKaXxu66SpTlIiEcq
oKSczyXsgmFtxXEca52nBextEhGKwHQBa2EAOoqX6Wx+nSoAAES3hMsFPi+b4fhZg73kBoBAQAjqcyBAU+6BJKAEEk
r+/6AcBVxZTFNJDPRTEsVFHFhTxbmsSFwlBD1fU4XhBFESRZEUVRNFBEqLQmaAgFJOy8SXIOUTbSeKSimhYTZPkKFP
jEooYMyyArBZCr9NNOyFqmWKtDyKn4h9k4idkJlNGJgNbTt3IyXWoCkRiMb4gmTkQE0ABqWyUTsqZbGiACaTSkeR+J
oqAFIjDSra+f5r3vZ932/Xu/3Aw6f4AcgJRNIdVxDpDMaFvhWzgC4WIOS0WN+uArRop6aJ800WL4imfr4mTj4vW9iA
fS0X1kbTOwtEcKtUxrNM6S0nHceuoAtGiZEAIqFp6iDZV1cihIDDNNKDu0Q2GNkblDbQw3DUvkYjKNoxj2O44tBNEz
KsopEc5PYYZZLGYzbUs/AbPHhzK4+6C3O8/zwCC0pwui+LkvS7L8uK3IU0MXMJr9H5Dpux74NWWGfsB/D5FyC3QOp+
7YTbZ7ncAnn3ew73LTlMESNw5R1FgkLItiwvbRL36XT9FkBYb1vK+l2vTSQJ6ABS8bI4vy1IsAKq3eecwS20dIEybk
PVOllv24gTQv2/NELQZZy09IWRAiYVJ0m6M7EI+8b7L2qKvcuZ9L5tGvpvW+sDghFjRNzRMGZgx1j1sddsT8AHvwqt
7Nctkv5+h/ogP+FCgEgKTGAiBTQoEwMjFkNoIUpaZllpbdKldEFVGzHmJo38JaMKaOjdi5Yd48JCA5FSWNQBCKlgGK
WYiJG+mkb/HSZYKxz0jCpcAPItgLw0eRLRoi/RZjPpIgxsi4TGKUa2Ouj4zgXCuI3OQnx7hzCyllR2etjhzEpmramW
tjam3CqrdWEspZiz+rAwJExgnAFupcCIoSf4pITsrCJTdTTInKRUypoBtT4BTrODalTGlNNWk4FwJgBDuCIAwCQfAe
BUE6QwQIIQTT12wlEj6bQyxJiTE3AYEg/wpGOMgM0pwgJNCWSUOYtYwxYHZBELAKp4J1l2SsBw1FEBYxNE0xpypSFn
iKKADZpVrkvP6HIB+ZCihzBTGmE21Q9GEWLGRP0iZ5FqJloomsoYAQnJscI7Ry1HG5n0fQmRf83GQvZLAM0CyllmhN
B8+53zUx90jNWbZML8imPJdCjYtp9ToGbKYzRIidEOP+U4lFDC/7pXAIgQsst3GlLiqgVACV/IFMLCbLKAKxZJkQJ6
aBwQAC8SLJFyoVdAroTs5n0TmC4v+Z8/Q/PIgSu5T8TWz0jEMJI0QKXLDMMy2xrLEUcuRVI1FhijXuKiGKB8VAzWPy
+Za0xNrohhF6scY4WBaBOvhfYtVXK0WnzCpCv1KRaCeIkPXfxEYYjIDFHiVAFJjjoGlEMckyq+BNQ5A+CtxJ+hgHtf
svZByUgEFoAATlEJQWgvbQAkEMGIZgYgsB2HHbYWgsh5ASCOTs1tKpiBkAoNQOgDAmDMCoMYIwnasBsCIJYaw4gpDS
EcM4Sg7hj2+HYAEBwch2pLNwMqhwAKDWRzllsKMd7s24HgPWB9yAn3VAAxuOQ9xephGVdUW0f7h7wEfZWe47zVTqng
BBqDVQQOVhVBENUso5ByD9NAOKeJm1yCxIOCIiFs6pDxG0eAEoWSgFlEUdswAmbtVFVcI50wZhyGLIgPE+R0DoHZMw
KIULJg7NQOhSI8GR5miwNqdAcgkbxBAikPEDhkHrwQX6b99Hqq1UHHiOQhmapAWwIBZAMRmTwGYHIFANRUB4mAIgao
4HaqgmAEUOsjmJhWcQrZlkpmJDgGOPUM0LmXBbGqDhvDaGvOwJkEAA==
LZS_PATCH


# cpu av8 av7 x86 x64
# NDK ++   .   .   .  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc

# Filelist
# --------
# include/librsync.h
# include/librsync_export.h
# lib/librsync.a
# lib/librsync.so
# lib/pkgconfig/librsync.pc
# share/doc/librsync/AUTHORS
# share/doc/librsync/COPYING
# share/doc/librsync/README.md