#!/bin/bash
# cpu av8 av7 x86 x64
# NDK  +   .   .   .  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc

lib='opencv'
dsc='Open Source Computer Vision Library'
lic='GLP-2.0'
src='https://github.com/opencv/opencv.git'
dep='libpng libjpeg'
cfg='cmake'
eta='860'

cmake_config="-DWITH_GTK=OFF -DWITH_1394=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DWITH_JPEG=ON -DBUILD_JPEG=OFF -DBUILD_JAVA=OFF -DBUILD_KOTLIN_EXTENSIONS=OFF"

dev_bra='master'
dev_vrs=''
stb_bra=''
stb_vrs=''

lst_inc=''
lst_lib=''
lst_bin=''
lst_lic='LICENSE COPYRIGHT'
lst_pc=''

. xbuilder.sh

$host_ndk && cmake_config+=' -DBUILD_ANDROID_EXAMPLES=OFF -DBUILD_ANDROID_PROJECTS=OFF'

start

# Filelist
# --------
# sdk/etc/valgrind_3rdparty.supp
# sdk/etc/lbpcascades/lbpcascade_frontalcatface.xml
# sdk/etc/lbpcascades/lbpcascade_profileface.xml
# sdk/etc/lbpcascades/lbpcascade_frontalface.xml
# sdk/etc/lbpcascades/lbpcascade_silverware.xml
# sdk/etc/lbpcascades/lbpcascade_frontalface_improved.xml
# sdk/etc/valgrind.supp
# sdk/etc/licenses/ittnotify-LICENSE.GPL
# sdk/etc/licenses/cpufeatures-LICENSE
# sdk/etc/licenses/cpufeatures-README.md
# sdk/etc/licenses/openexr-LICENSE
# sdk/etc/licenses/ade-LICENSE
# sdk/etc/licenses/SoftFloat-COPYING.txt
# sdk/etc/licenses/libopenjp2-LICENSE
# sdk/etc/licenses/quirc-LICENSE
# sdk/etc/licenses/libopenjp2-README.md
# sdk/etc/licenses/libpng-LICENSE
# sdk/etc/licenses/libtiff-COPYRIGHT
# sdk/etc/licenses/openexr-AUTHORS.ilmbase
# sdk/etc/licenses/ittnotify-LICENSE.BSD
# sdk/etc/licenses/protobuf-LICENSE
# sdk/etc/licenses/openexr-AUTHORS.openexr
# sdk/etc/licenses/libpng-README
# sdk/etc/licenses/protobuf-README.md
# sdk/etc/haarcascades/haarcascade_upperbody.xml
# sdk/etc/haarcascades/haarcascade_eye.xml
# sdk/etc/haarcascades/haarcascade_frontalface_alt.xml
# sdk/etc/haarcascades/haarcascade_frontalface_alt2.xml
# sdk/etc/haarcascades/haarcascade_fullbody.xml
# sdk/etc/haarcascades/haarcascade_lowerbody.xml
# sdk/etc/haarcascades/haarcascade_lefteye_2splits.xml
# sdk/etc/haarcascades/haarcascade_smile.xml
# sdk/etc/haarcascades/haarcascade_righteye_2splits.xml
# sdk/etc/haarcascades/haarcascade_frontalface_alt_tree.xml
# sdk/etc/haarcascades/haarcascade_licence_plate_rus_16stages.xml
# sdk/etc/haarcascades/haarcascade_frontalface_default.xml
# sdk/etc/haarcascades/haarcascade_frontalcatface_extended.xml
# sdk/etc/haarcascades/haarcascade_russian_plate_number.xml
# sdk/etc/haarcascades/haarcascade_eye_tree_eyeglasses.xml
# sdk/etc/haarcascades/haarcascade_frontalcatface.xml
# sdk/etc/haarcascades/haarcascade_profileface.xml
# sdk/native/jni/include/opencv2/core.hpp
# sdk/native/jni/include/opencv2/gapi.hpp
# sdk/native/jni/include/opencv2/gapi/gasync_context.hpp
# sdk/native/jni/include/opencv2/gapi/core.hpp
# sdk/native/jni/include/opencv2/gapi/render/render.hpp
# sdk/native/jni/include/opencv2/gapi/render/render_types.hpp
# sdk/native/jni/include/opencv2/gapi/render.hpp
# sdk/native/jni/include/opencv2/gapi/opencv_includes.hpp
# sdk/native/jni/include/opencv2/gapi/gcompoundkernel.hpp
# sdk/native/jni/include/opencv2/gapi/stereo.hpp
# sdk/native/jni/include/opencv2/gapi/gcompiled_async.hpp
# sdk/native/jni/include/opencv2/gapi/gscalar.hpp
# sdk/native/jni/include/opencv2/gapi/own/saturate.hpp
# sdk/native/jni/include/opencv2/gapi/own/cvdefs.hpp
# sdk/native/jni/include/opencv2/gapi/own/exports.hpp
# sdk/native/jni/include/opencv2/gapi/own/scalar.hpp
# sdk/native/jni/include/opencv2/gapi/own/convert.hpp
# sdk/native/jni/include/opencv2/gapi/own/mat.hpp
# sdk/native/jni/include/opencv2/gapi/own/types.hpp
# sdk/native/jni/include/opencv2/gapi/own/assert.hpp
# sdk/native/jni/include/opencv2/gapi/rmat.hpp
# sdk/native/jni/include/opencv2/gapi/fluid/core.hpp
# sdk/native/jni/include/opencv2/gapi/fluid/imgproc.hpp
# sdk/native/jni/include/opencv2/gapi/fluid/gfluidkernel.hpp
# sdk/native/jni/include/opencv2/gapi/fluid/gfluidbuffer.hpp
# sdk/native/jni/include/opencv2/gapi/gcomputation_async.hpp
# sdk/native/jni/include/opencv2/gapi/gproto.hpp
# sdk/native/jni/include/opencv2/gapi/garray.hpp
# sdk/native/jni/include/opencv2/gapi/operators.hpp
# sdk/native/jni/include/opencv2/gapi/gstreaming.hpp
# sdk/native/jni/include/opencv2/gapi/s11n.hpp
# sdk/native/jni/include/opencv2/gapi/gmetaarg.hpp
# sdk/native/jni/include/opencv2/gapi/gframe.hpp
# sdk/native/jni/include/opencv2/gapi/cpu/core.hpp
# sdk/native/jni/include/opencv2/gapi/cpu/stereo.hpp
# sdk/native/jni/include/opencv2/gapi/cpu/gcpukernel.hpp
# sdk/native/jni/include/opencv2/gapi/cpu/imgproc.hpp
# sdk/native/jni/include/opencv2/gapi/cpu/video.hpp
# sdk/native/jni/include/opencv2/gapi/gmat.hpp
# sdk/native/jni/include/opencv2/gapi/infer.hpp
# sdk/native/jni/include/opencv2/gapi/infer/ie.hpp
# sdk/native/jni/include/opencv2/gapi/infer/onnx.hpp
# sdk/native/jni/include/opencv2/gapi/infer/parsers.hpp
# sdk/native/jni/include/opencv2/gapi/infer/bindings_ie.hpp
# sdk/native/jni/include/opencv2/gapi/gcompiled.hpp
# sdk/native/jni/include/opencv2/gapi/plaidml/core.hpp
# sdk/native/jni/include/opencv2/gapi/plaidml/gplaidmlkernel.hpp
# sdk/native/jni/include/opencv2/gapi/plaidml/plaidml.hpp
# sdk/native/jni/include/opencv2/gapi/gtransform.hpp
# sdk/native/jni/include/opencv2/gapi/gtype_traits.hpp
# sdk/native/jni/include/opencv2/gapi/util/util.hpp
# sdk/native/jni/include/opencv2/gapi/util/any.hpp
# sdk/native/jni/include/opencv2/gapi/util/throw.hpp
# sdk/native/jni/include/opencv2/gapi/util/optional.hpp
# sdk/native/jni/include/opencv2/gapi/util/variant.hpp
# sdk/native/jni/include/opencv2/gapi/util/type_traits.hpp
# sdk/native/jni/include/opencv2/gapi/util/compiler_hints.hpp
# sdk/native/jni/include/opencv2/gapi/util/copy_through_move.hpp
# sdk/native/jni/include/opencv2/gapi/garg.hpp
# sdk/native/jni/include/opencv2/gapi/gkernel.hpp
# sdk/native/jni/include/opencv2/gapi/imgproc.hpp
# sdk/native/jni/include/opencv2/gapi/gtyped.hpp
# sdk/native/jni/include/opencv2/gapi/gopaque.hpp
# sdk/native/jni/include/opencv2/gapi/python/python.hpp
# sdk/native/jni/include/opencv2/gapi/gcall.hpp
# sdk/native/jni/include/opencv2/gapi/s11n/base.hpp
# sdk/native/jni/include/opencv2/gapi/gcomputation.hpp
# sdk/native/jni/include/opencv2/gapi/media.hpp
# sdk/native/jni/include/opencv2/gapi/gcommon.hpp
# sdk/native/jni/include/opencv2/gapi/gpu/core.hpp
# sdk/native/jni/include/opencv2/gapi/gpu/ggpukernel.hpp
# sdk/native/jni/include/opencv2/gapi/gpu/imgproc.hpp
# sdk/native/jni/include/opencv2/gapi/streaming/cap.hpp
# sdk/native/jni/include/opencv2/gapi/streaming/source.hpp
# sdk/native/jni/include/opencv2/gapi/streaming/sync.hpp
# sdk/native/jni/include/opencv2/gapi/streaming/desync.hpp
# sdk/native/jni/include/opencv2/gapi/streaming/format.hpp
# sdk/native/jni/include/opencv2/gapi/streaming/meta.hpp
# sdk/native/jni/include/opencv2/gapi/ocl/core.hpp
# sdk/native/jni/include/opencv2/gapi/ocl/imgproc.hpp
# sdk/native/jni/include/opencv2/gapi/ocl/goclkernel.hpp
# sdk/native/jni/include/opencv2/gapi/video.hpp
# sdk/native/jni/include/opencv2/dnn.hpp
# sdk/native/jni/include/opencv2/cvconfig.h
# sdk/native/jni/include/opencv2/calib3d.hpp
# sdk/native/jni/include/opencv2/stitching/warpers.hpp
# sdk/native/jni/include/opencv2/stitching/detail/warpers_inl.hpp
# sdk/native/jni/include/opencv2/stitching/detail/util.hpp
# sdk/native/jni/include/opencv2/stitching/detail/util_inl.hpp
# sdk/native/jni/include/opencv2/stitching/detail/exposure_compensate.hpp
# sdk/native/jni/include/opencv2/stitching/detail/seam_finders.hpp
# sdk/native/jni/include/opencv2/stitching/detail/warpers.hpp
# sdk/native/jni/include/opencv2/stitching/detail/timelapsers.hpp
# sdk/native/jni/include/opencv2/stitching/detail/motion_estimators.hpp
# sdk/native/jni/include/opencv2/stitching/detail/matchers.hpp
# sdk/native/jni/include/opencv2/stitching/detail/autocalib.hpp
# sdk/native/jni/include/opencv2/stitching/detail/blenders.hpp
# sdk/native/jni/include/opencv2/stitching/detail/camera.hpp
# sdk/native/jni/include/opencv2/objdetect/face.hpp
# sdk/native/jni/include/opencv2/objdetect/detection_based_tracker.hpp
# sdk/native/jni/include/opencv2/objdetect/objdetect.hpp
# sdk/native/jni/include/opencv2/highgui.hpp
# sdk/native/jni/include/opencv2/features2d.hpp
# sdk/native/jni/include/opencv2/flann/params.h
# sdk/native/jni/include/opencv2/flann/saving.h
# sdk/native/jni/include/opencv2/flann/composite_index.h
# sdk/native/jni/include/opencv2/flann/allocator.h
# sdk/native/jni/include/opencv2/flann/nn_index.h
# sdk/native/jni/include/opencv2/flann/all_indices.h
# sdk/native/jni/include/opencv2/flann/kdtree_index.h
# sdk/native/jni/include/opencv2/flann/defines.h
# sdk/native/jni/include/opencv2/flann/linear_index.h
# sdk/native/jni/include/opencv2/flann/logger.h
# sdk/native/jni/include/opencv2/flann/config.h
# sdk/native/jni/include/opencv2/flann/dynamic_bitset.h
# sdk/native/jni/include/opencv2/flann/random.h
# sdk/native/jni/include/opencv2/flann/ground_truth.h
# sdk/native/jni/include/opencv2/flann/kmeans_index.h
# sdk/native/jni/include/opencv2/flann/dist.h
# sdk/native/jni/include/opencv2/flann/matrix.h
# sdk/native/jni/include/opencv2/flann/any.h
# sdk/native/jni/include/opencv2/flann/hdf5.h
# sdk/native/jni/include/opencv2/flann/flann.hpp
# sdk/native/jni/include/opencv2/flann/heap.h
# sdk/native/jni/include/opencv2/flann/dummy.h
# sdk/native/jni/include/opencv2/flann/simplex_downhill.h
# sdk/native/jni/include/opencv2/flann/index_testing.h
# sdk/native/jni/include/opencv2/flann/hierarchical_clustering_index.h
# sdk/native/jni/include/opencv2/flann/timer.h
# sdk/native/jni/include/opencv2/flann/autotuned_index.h
# sdk/native/jni/include/opencv2/flann/lsh_table.h
# sdk/native/jni/include/opencv2/flann/general.h
# sdk/native/jni/include/opencv2/flann/object_factory.h
# sdk/native/jni/include/opencv2/flann/flann_base.hpp
# sdk/native/jni/include/opencv2/flann/kdtree_single_index.h
# sdk/native/jni/include/opencv2/flann/miniflann.hpp
# sdk/native/jni/include/opencv2/flann/lsh_index.h
# sdk/native/jni/include/opencv2/flann/result_set.h
# sdk/native/jni/include/opencv2/flann/sampling.h
# sdk/native/jni/include/opencv2/features2d/features2d.hpp
# sdk/native/jni/include/opencv2/features2d/hal/interface.h
# sdk/native/jni/include/opencv2/imgcodecs/imgcodecs_c.h
# sdk/native/jni/include/opencv2/imgcodecs/ios.h
# sdk/native/jni/include/opencv2/imgcodecs/legacy/constants_c.h
# sdk/native/jni/include/opencv2/imgcodecs/imgcodecs.hpp
# sdk/native/jni/include/opencv2/imgcodecs/macosx.h
# sdk/native/jni/include/opencv2/videoio/legacy/constants_c.h
# sdk/native/jni/include/opencv2/videoio/videoio_c.h
# sdk/native/jni/include/opencv2/videoio/videoio.hpp
# sdk/native/jni/include/opencv2/videoio/cap_ios.h
# sdk/native/jni/include/opencv2/videoio/registry.hpp
# sdk/native/jni/include/opencv2/calib3d/calib3d.hpp
# sdk/native/jni/include/opencv2/calib3d/calib3d_c.h
# sdk/native/jni/include/opencv2/videoio.hpp
# sdk/native/jni/include/opencv2/video/legacy/constants_c.h
# sdk/native/jni/include/opencv2/video/tracking.hpp
# sdk/native/jni/include/opencv2/video/background_segm.hpp
# sdk/native/jni/include/opencv2/video/detail/tracking.detail.hpp
# sdk/native/jni/include/opencv2/video/video.hpp
# sdk/native/jni/include/opencv2/flann.hpp
# sdk/native/jni/include/opencv2/ml/ml.hpp
# sdk/native/jni/include/opencv2/ml/ml.inl.hpp
# sdk/native/jni/include/opencv2/imgcodecs.hpp
# sdk/native/jni/include/opencv2/photo.hpp
# sdk/native/jni/include/opencv2/stitching.hpp
# sdk/native/jni/include/opencv2/opencv.hpp
# sdk/native/jni/include/opencv2/imgproc.hpp
# sdk/native/jni/include/opencv2/imgproc/bindings.hpp
# sdk/native/jni/include/opencv2/imgproc/imgproc_c.h
# sdk/native/jni/include/opencv2/imgproc/imgproc.hpp
# sdk/native/jni/include/opencv2/imgproc/types_c.h
# sdk/native/jni/include/opencv2/imgproc/segmentation.hpp
# sdk/native/jni/include/opencv2/imgproc/hal/hal.hpp
# sdk/native/jni/include/opencv2/imgproc/hal/interface.h
# sdk/native/jni/include/opencv2/imgproc/detail/gcgraph.hpp
# sdk/native/jni/include/opencv2/dnn/dnn.hpp
# sdk/native/jni/include/opencv2/dnn/all_layers.hpp
# sdk/native/jni/include/opencv2/dnn/layer.hpp
# sdk/native/jni/include/opencv2/dnn/utils/inference_engine.hpp
# sdk/native/jni/include/opencv2/dnn/utils/debug_utils.hpp
# sdk/native/jni/include/opencv2/dnn/dnn.inl.hpp
# sdk/native/jni/include/opencv2/dnn/dict.hpp
# sdk/native/jni/include/opencv2/dnn/shape_utils.hpp
# sdk/native/jni/include/opencv2/dnn/version.hpp
# sdk/native/jni/include/opencv2/dnn/layer.details.hpp
# sdk/native/jni/include/opencv2/photo/legacy/constants_c.h
# sdk/native/jni/include/opencv2/photo/photo.hpp
# sdk/native/jni/include/opencv2/photo/cuda.hpp
# sdk/native/jni/include/opencv2/core/quaternion.inl.hpp
# sdk/native/jni/include/opencv2/core/core.hpp
# sdk/native/jni/include/opencv2/core/simd_intrinsics.hpp
# sdk/native/jni/include/opencv2/core/saturate.hpp
# sdk/native/jni/include/opencv2/core/cuda_stream_accessor.hpp
# sdk/native/jni/include/opencv2/core/operations.hpp
# sdk/native/jni/include/opencv2/core/cvstd_wrapper.hpp
# sdk/native/jni/include/opencv2/core/cv_cpu_dispatch.h
# sdk/native/jni/include/opencv2/core/ovx.hpp
# sdk/native/jni/include/opencv2/core/sse_utils.hpp
# sdk/native/jni/include/opencv2/core/traits.hpp
# sdk/native/jni/include/opencv2/core/neon_utils.hpp
# sdk/native/jni/include/opencv2/core/dualquaternion.hpp
# sdk/native/jni/include/opencv2/core/optim.hpp
# sdk/native/jni/include/opencv2/core/va_intel.hpp
# sdk/native/jni/include/opencv2/core/bindings_utils.hpp
# sdk/native/jni/include/opencv2/core/utility.hpp
# sdk/native/jni/include/opencv2/core/matx.hpp
# sdk/native/jni/include/opencv2/core/eigen.hpp
# sdk/native/jni/include/opencv2/core/bufferpool.hpp
# sdk/native/jni/include/opencv2/core/affine.hpp
# sdk/native/jni/include/opencv2/core/directx.hpp
# sdk/native/jni/include/opencv2/core/softfloat.hpp
# sdk/native/jni/include/opencv2/core/cvstd.hpp
# sdk/native/jni/include/opencv2/core/opencl/opencl_svm.hpp
# sdk/native/jni/include/opencv2/core/opencl/runtime/opencl_gl_wrappers.hpp
# sdk/native/jni/include/opencv2/core/opencl/runtime/opencl_clblas.hpp
# sdk/native/jni/include/opencv2/core/opencl/runtime/opencl_svm_definitions.hpp
# sdk/native/jni/include/opencv2/core/opencl/runtime/opencl_gl.hpp
# sdk/native/jni/include/opencv2/core/opencl/runtime/opencl_svm_20.hpp
# sdk/native/jni/include/opencv2/core/opencl/runtime/opencl_clfft.hpp
# sdk/native/jni/include/opencv2/core/opencl/runtime/opencl_core_wrappers.hpp
# sdk/native/jni/include/opencv2/core/opencl/runtime/opencl_core.hpp
# sdk/native/jni/include/opencv2/core/opencl/runtime/autogenerated/opencl_gl_wrappers.hpp
# sdk/native/jni/include/opencv2/core/opencl/runtime/autogenerated/opencl_clblas.hpp
# sdk/native/jni/include/opencv2/core/opencl/runtime/autogenerated/opencl_gl.hpp
# sdk/native/jni/include/opencv2/core/opencl/runtime/autogenerated/opencl_clfft.hpp
# sdk/native/jni/include/opencv2/core/opencl/runtime/autogenerated/opencl_core_wrappers.hpp
# sdk/native/jni/include/opencv2/core/opencl/runtime/autogenerated/opencl_core.hpp
# sdk/native/jni/include/opencv2/core/opencl/runtime/opencl_svm_hsa_extension.hpp
# sdk/native/jni/include/opencv2/core/opencl/opencl_info.hpp
# sdk/native/jni/include/opencv2/core/opencl/ocl_defs.hpp
# sdk/native/jni/include/opencv2/core/cuda_types.hpp
# sdk/native/jni/include/opencv2/core/persistence.hpp
# sdk/native/jni/include/opencv2/core/utils/logger.hpp
# sdk/native/jni/include/opencv2/core/utils/logtag.hpp
# sdk/native/jni/include/opencv2/core/utils/tls.hpp
# sdk/native/jni/include/opencv2/core/utils/allocator_stats.hpp
# sdk/native/jni/include/opencv2/core/utils/instrumentation.hpp
# sdk/native/jni/include/opencv2/core/utils/filesystem.hpp
# sdk/native/jni/include/opencv2/core/utils/logger.defines.hpp
# sdk/native/jni/include/opencv2/core/utils/allocator_stats.impl.hpp
# sdk/native/jni/include/opencv2/core/utils/trace.hpp
# sdk/native/jni/include/opencv2/core/vsx_utils.hpp
# sdk/native/jni/include/opencv2/core/cuda.inl.hpp
# sdk/native/jni/include/opencv2/core/cuda.hpp
# sdk/native/jni/include/opencv2/core/types_c.h
# sdk/native/jni/include/opencv2/core/dualquaternion.inl.hpp
# sdk/native/jni/include/opencv2/core/cvdef.h
# sdk/native/jni/include/opencv2/core/hal/intrin_sse_em.hpp
# sdk/native/jni/include/opencv2/core/hal/intrin_neon.hpp
# sdk/native/jni/include/opencv2/core/hal/hal.hpp
# sdk/native/jni/include/opencv2/core/hal/intrin_rvv071.hpp
# sdk/native/jni/include/opencv2/core/hal/intrin_msa.hpp
# sdk/native/jni/include/opencv2/core/hal/intrin_wasm.hpp
# sdk/native/jni/include/opencv2/core/hal/simd_utils.impl.hpp
# sdk/native/jni/include/opencv2/core/hal/intrin.hpp
# sdk/native/jni/include/opencv2/core/hal/intrin_avx.hpp
# sdk/native/jni/include/opencv2/core/hal/interface.h
# sdk/native/jni/include/opencv2/core/hal/intrin_avx512.hpp
# sdk/native/jni/include/opencv2/core/hal/intrin_cpp.hpp
# sdk/native/jni/include/opencv2/core/hal/msa_macros.h
# sdk/native/jni/include/opencv2/core/hal/intrin_rvv.hpp
# sdk/native/jni/include/opencv2/core/hal/intrin_vsx.hpp
# sdk/native/jni/include/opencv2/core/hal/intrin_sse.hpp
# sdk/native/jni/include/opencv2/core/hal/intrin_forward.hpp
# sdk/native/jni/include/opencv2/core/async.hpp
# sdk/native/jni/include/opencv2/core/cuda/block.hpp
# sdk/native/jni/include/opencv2/core/cuda/transform.hpp
# sdk/native/jni/include/opencv2/core/cuda/saturate_cast.hpp
# sdk/native/jni/include/opencv2/core/cuda/warp_shuffle.hpp
# sdk/native/jni/include/opencv2/core/cuda/emulation.hpp
# sdk/native/jni/include/opencv2/core/cuda/dynamic_smem.hpp
# sdk/native/jni/include/opencv2/core/cuda/common.hpp
# sdk/native/jni/include/opencv2/core/cuda/limits.hpp
# sdk/native/jni/include/opencv2/core/cuda/utility.hpp
# sdk/native/jni/include/opencv2/core/cuda/border_interpolate.hpp
# sdk/native/jni/include/opencv2/core/cuda/simd_functions.hpp
# sdk/native/jni/include/opencv2/core/cuda/type_traits.hpp
# sdk/native/jni/include/opencv2/core/cuda/vec_traits.hpp
# sdk/native/jni/include/opencv2/core/cuda/functional.hpp
# sdk/native/jni/include/opencv2/core/cuda/vec_distance.hpp
# sdk/native/jni/include/opencv2/core/cuda/funcattrib.hpp
# sdk/native/jni/include/opencv2/core/cuda/scan.hpp
# sdk/native/jni/include/opencv2/core/cuda/vec_math.hpp
# sdk/native/jni/include/opencv2/core/cuda/detail/color_detail.hpp
# sdk/native/jni/include/opencv2/core/cuda/detail/reduce_key_val.hpp
# sdk/native/jni/include/opencv2/core/cuda/detail/type_traits_detail.hpp
# sdk/native/jni/include/opencv2/core/cuda/detail/vec_distance_detail.hpp
# sdk/native/jni/include/opencv2/core/cuda/detail/transform_detail.hpp
# sdk/native/jni/include/opencv2/core/cuda/detail/reduce.hpp
# sdk/native/jni/include/opencv2/core/cuda/datamov_utils.hpp
# sdk/native/jni/include/opencv2/core/cuda/warp.hpp
# sdk/native/jni/include/opencv2/core/cuda/warp_reduce.hpp
# sdk/native/jni/include/opencv2/core/cuda/color.hpp
# sdk/native/jni/include/opencv2/core/cuda/filters.hpp
# sdk/native/jni/include/opencv2/core/cuda/reduce.hpp
# sdk/native/jni/include/opencv2/core/mat.hpp
# sdk/native/jni/include/opencv2/core/mat.inl.hpp
# sdk/native/jni/include/opencv2/core/check.hpp
# sdk/native/jni/include/opencv2/core/base.hpp
# sdk/native/jni/include/opencv2/core/cvstd.inl.hpp
# sdk/native/jni/include/opencv2/core/fast_math.hpp
# sdk/native/jni/include/opencv2/core/detail/exception_ptr.hpp
# sdk/native/jni/include/opencv2/core/detail/async_promise.hpp
# sdk/native/jni/include/opencv2/core/types.hpp
# sdk/native/jni/include/opencv2/core/parallel/backend/parallel_for.tbb.hpp
# sdk/native/jni/include/opencv2/core/parallel/backend/parallel_for.openmp.hpp
# sdk/native/jni/include/opencv2/core/parallel/parallel_backend.hpp
# sdk/native/jni/include/opencv2/core/version.hpp
# sdk/native/jni/include/opencv2/core/ocl_genbase.hpp
# sdk/native/jni/include/opencv2/core/ocl.hpp
# sdk/native/jni/include/opencv2/core/cv_cpu_helper.h
# sdk/native/jni/include/opencv2/core/opengl.hpp
# sdk/native/jni/include/opencv2/core/quaternion.hpp
# sdk/native/jni/include/opencv2/core/core_c.h
# sdk/native/jni/include/opencv2/highgui/highgui.hpp
# sdk/native/jni/include/opencv2/highgui/highgui_c.h
# sdk/native/jni/include/opencv2/opencv_modules.hpp
# sdk/native/jni/include/opencv2/ml.hpp
# sdk/native/jni/include/opencv2/objdetect.hpp
# sdk/native/jni/include/opencv2/video.hpp
# sdk/native/jni/OpenCVConfig.cmake
# sdk/native/jni/abi-arm64-v8a/OpenCVConfig.cmake
# sdk/native/jni/abi-arm64-v8a/OpenCVConfig-version.cmake
# sdk/native/jni/abi-arm64-v8a/OpenCVModules.cmake
# sdk/native/jni/abi-arm64-v8a/OpenCVModules-release.cmake
# sdk/native/jni/OpenCVConfig-version.cmake
# sdk/native/jni/android.toolchain.cmake
# sdk/native/jni/OpenCV-arm64-v8a.mk
# sdk/native/jni/OpenCV.mk
# sdk/native/libs/arm64-v8a/libopencv_flann.so
# sdk/native/libs/arm64-v8a/libopencv_core.so
# sdk/native/libs/arm64-v8a/libopencv_videoio.so
# sdk/native/libs/arm64-v8a/libopencv_objdetect.so
# sdk/native/libs/arm64-v8a/libopencv_stitching.so
# sdk/native/libs/arm64-v8a/libopencv_dnn.so
# sdk/native/libs/arm64-v8a/libopencv_features2d.so
# sdk/native/libs/arm64-v8a/libopencv_calib3d.so
# sdk/native/libs/arm64-v8a/libopencv_ml.so
# sdk/native/libs/arm64-v8a/libopencv_gapi.so
# sdk/native/libs/arm64-v8a/libopencv_highgui.so
# sdk/native/libs/arm64-v8a/libopencv_imgcodecs.so
# sdk/native/libs/arm64-v8a/libopencv_video.so
# sdk/native/libs/arm64-v8a/libopencv_photo.so
# sdk/native/libs/arm64-v8a/libopencv_imgproc.so
# LICENSE
# README.android
