#!/bin/bash
# cpu av8 av7 x86 x64
# NDK  .   .   .  PP  clang
# GNU  .   .   .  PP  gcc
# WIN  .   .   .  PP  clang/gcc

lib='uavs3e'
dsc='AVS3 encoder which supports AVS3-P2 baseline profile.'
lic='Other'
src='https://github.com/uavs3/uavs3e.git'
cfg='cmake'
eta='0'

cmake_config='-DCOMPILE_10BIT=1'
cmake_static='-DBUILD_SHARED_LIBS=0'

lst_inc=''
lst_lib=''
lst_bin=''
dev_vrs='1.3.1'

_on_config_arm(){
    doErr "Arm not supported."
}

. xbuild

start

<<'LZS_PATCH_IGNORE'
LQgEGEFkEMGsFMAyBLAzgF1QOgPYBsATASACYAGEgRmErOAGYzQSSAuMgDlfoDYsyA7AE4yosaADUZWmQBQEhRBgIU
GbOgAe6UhWq0GTFuy4BWPiQEmyAFh6MmUmbIACz0DQA0AyZS+hXsqAAxgC2cPAA+iHIAHbIIQCuIREATvAAjgnIaQQ
AFABqAKIASgDKAJIA8gByzFgcAJSBgQAOKTgAVvBB6LkJ0ABuqPTwTcDy0AQEEUE4IS3IeJE4LejIODGoucAA6jE4w
C04sejwKcCoyADmMe57BwkxCajwBMAD0HgJ8Hf7wHg4K7IIKfYD7dCHaBpGLoAAW8BeqF+B1QsOQADMITF4FdoGsBv
B3p9vsjgLFZvM8cgAEZLQ7HGFnYDoACeLQRpNmm3Q0BhwC5BJSlw2TVA0ASGgiqBwCRSQUiBGy3XQOBSLNyWAA9KcM
KAACLlYoRUrFcARAAqhVK5tFL3QUplcsi6MWCIibRWZzWCNyABIAN4Go0ms2W60AX1AAAVipUoyVzeUrRBKpAo+VEI
UIgAxRAAQQA4qVQAAiANQPMAaSzZtzhdKkfcGAIAF4gkIhO5KvQS01ZCBgKBUHLNVBwqpMLhCDoqDQ6JQOKBpOweKx
KAIsAI7Ou7KJJNJRPJFMOgqPlEg0JPNNpyLP9Aul5QV2u+JQhPQd/Z905XO5aB5Owkf9KBIfxnGaUByS+AgFSVHpVW
QH0SywLVyV7ZoLnge1pVleUIhdJZUHddp2RSb0tgDIMIgAVTzfJSnoLMQ0jGM4wTJNi3AVN00zHN8yLUty0gKsaz4+
tI2AdF03AJt0FbdtO2Abt0Mw7DHTwgi3Q9UjyL9QNDQiAANDgeGNU0WNjeNikTZMuLTDMszrASy39CtqwiWt+Ibdwp
PKGSLjktsOy7eh3BCVAXmsLASBUu0HVw51XSI7SvUQij9KNYzTJIMwzPACy2OsjiU3s3inOLFy3NE8qJN8/zmyCxTu
zCwYNBipoJAxXJqkqc1QB2cpqnoEgOtAIcsNybNpNLSTpPQiR4BiRV0VyDq4pwp18KS4jPTItK9Ko2j6MYvKCqsmzO
O4hyxOcoSRI8m7vIDKa/IkhqFJC+b1vUxLCJ2nT9sogystO6NLPY2yrrKrzBNc4T3M88TQGe6S3sCj6lNC4Bwsi6Kv
qw+LNs05KSNSn0gcykyIhy0zmLBwqLpKnjHJhyr4eqrzIxR17ZPk4LMZagY2vQ0BAgAYlAK4sNAQVhRiQI7VAXIuOq
bNygLCIg2RuH7vAajimKQpqnNY1Kn18AsyDcNNRQvsB0gmJTwpKUWQweAQiwWEZz0OhGGYJ9bHYExNxIawxHERxDwU
CQHaduYXbdj2vdvH2DH91hA7fLArCsWwv0juRfxoHhfG8ICS78AJQDFmCXWxYJ4/CgmNBAjhcgIDAPAGDxLgAL1GUA
Qndu1cnbjAGg8JWBgnpW+9GUUa/gOufmdkJQhaMf0B7uUe+QfuGjGsah7X+ZR479AZ9yE9L7nhpRX7MWMVAWvYleXI
IgiAtqmos0Ig6x/0TPyXq/PIH8v4/w/gfAAZFA0AABCF+2JQERDzNUPUsZyh6kgeLRBPwcDonRHafBV8PAhAPh/akW
Q8BrBiBEfBhCsLENQKQhei1lqyH7GAckmpnZwjSJMT23s5xpyMGQEwa4NzWEsOHPcBcjwx24bw2E/CCCCJTsIv2ojV
wfnqNYXOu4HAHkLm4YAJB6B+AkGYyu4FRbV3gHgF4GExZtGgFcMIDcQhDxhLkPANJJ4llWMo+Akx8jgBIFgXx1J5qa
k1M4lIrj3EUi8b0SJ/jAkqNCeEyJItxZQQSDBUAAAeF4YQWiwlVPAT2AA+XJjtoI/EKek4JqjYQ1KAA=
LZS_PATCH_IGNORE

# Filelist
# --------
# include/uavs3e/uavs3e.h
# include/uavs3e/com_api.h
# lib/pkgconfig/uavs3e.pc
# lib/libuavs3e.so

