#!/bin/bash
# cpu av8 av7 x86 x64
# NDK N/A N/A  .   .  clang
# GNU N/A N/A  .   .  gcc
# WIN N/A N/A  .   .  clang/gcc

lib='xeve'
dsc='eXtra-fast Essential Video Encoder, MPEG-5 EVC (Essential Video Coding)'
lic='Other'
src='https://github.com/mpeg5/xeve.git'
cfg='cmake'
cmake_static="XEVE_APP_STATIC_BUILD"

lst_inc='xeve/*.h'
lst_lib='libxeve'
lst_bin='xeve_app'
lst_lic='COPYING'
lst_pc='vpx.pc'

dev_bra='main'
dev_vrs=''
stb_bra=''
stb_vrs='1.11.0'

. xbuild

# see https://github.com/lighttransport/embree-aarch64/blob/master/common/math/SSE2NEON.h
# and https://github.com/lighttransport/embree-aarch64/blob/master/common/math/AVX2NEON.h
# port AVX/SSE port to aarch64

$host_arm && doErr "${lib} does not support cross-build for arm (${arch})."
$host_native && cmake_config='-DXEVE_NATIVE_BUILD=ON'

start

# patch 01 on CMakeLists.txt to remove werrors in clang and implement native build
# option XEVE_NATIVE_BUILD
<<'XB64_PATCH'
LS0tIENNYWtlTGlzdHMudHh0CTIwMjItMDItMjQgMTk6MjE6MjYuMTExMDY1NTAwICswMDAwCisr
KyBDTWFrZUxpc3RzLnR4dAkyMDIyLTAyLTI0IDE5OjMyOjQ2LjIyMTA2NTUwMCArMDAwMApAQCAt
MTMsNiArMTMsMTEgQEAKIGVuZGlmKCkKIAogb3B0aW9uKFhFVkVfQVBQX1NUQVRJQ19CVUlMRCAi
eGV2ZV9hcHAgd2lsbCBiZSBzdGF0aWNhbGx5IGxpbmtlZCBhZ2FpbnN0IHN0YXRpYyB4ZXZlIGxp
YnJhcnkiIE9OKQorCitpZihOT1QgQ01BS0VfQ1JPU1NDT01QSUxJTkcpCisgIG9wdGlvbihYRVZF
X05BVElWRV9CVUlMRCAieGV2ZSB3aWxsIGJlIG5hdGl2ZWx5IGNvbXBpbGVkICIgT04pCitlbmRp
ZigpCisKIGlmKFhFVkVfQVBQX1NUQVRJQ19CVUlMRCkKICAgICBhZGRfZGVmaW5pdGlvbnMoLURY
RVZFX1NUQVRJQ19ERUZJTkUpCiBlbmRpZihYRVZFX0FQUF9TVEFUSUNfQlVJTEQpCkBAIC00MCw4
ICs0NSwyMiBAQAogICAgICAgICBzZXQoT1BUX0RCRyAiLUROREVCVUciKSAjIGRpc2FibGUgYXNz
ZXJ0IAogICAgIGVuZGlmKCkKIAotICAgIHNldCAoQ01BS0VfQ19GTEFHUyAiJHtDTUFLRV9DX0ZM
QUdTfSAke09QVF9EQkd9IC0ke09QVF9MVn0gLWZvbWl0LWZyYW1lLXBvaW50ZXIgLVdhbGwgLVdu
by11bnVzZWQtZnVuY3Rpb24gLVduby11bnVzZWQtYnV0LXNldC12YXJpYWJsZSAtV25vLXVudXNl
ZC12YXJpYWJsZSAtV25vLWF0dHJpYnV0ZXMgLVdlcnJvciAtV25vLXN0cmljdC1vdmVyZmxvdyAt
V25vLXVua25vd24tcHJhZ21hcyAtV25vLXN0cmluZ29wLW92ZXJmbG93IC1zdGQ9Yzk5IikKLSAg
ICBzZXQgKENNQUtFX0NfRkxBR1MgIiR7Q01BS0VfQ19GTEFHU30gLVduby1wb2ludGVyLXNpZ24g
LXB0aHJlYWQgLVduby1wb2ludGVyLXRvLWludC1jYXN0IC1Xbm8tbWF5YmUtdW5pbml0aWFsaXpl
ZCIpCisgICAgaWYoQ01BS0VfQ1hYX0NPTVBJTEVSX0lEIFNUUkVRVUFMICJDbGFuZyIpCisgICAg
ICAgIHNldChPUFRfVzAgIi1Xbm8tdW51c2VkLWNvbnN0LXZhcmlhYmxlIC1Xbm8tc2hpZnQtb3Zl
cmZsb3ciKQorICAgICAgICBzZXQoT1BUX1cxICItV25vLXVuaW5pdGlhbGl6ZWQiKQorICAgICAg
ICBzZXQoT1BUX00gInR1bmUiKQorICAgIGVsc2UoKQorICAgICAgICBzZXQoT1BUX1cwICItV25v
LXVudXNlZC1idXQtc2V0LXZhcmlhYmxlIC1Xbm8tc3RyaW5nb3Atb3ZlcmZsb3ciKQorICAgICAg
ICBzZXQoT1BUX1cxICItV25vLW1heWJlLXVuaW5pdGlhbGl6ZWQiKQorICAgICAgICBzZXQoT1BU
X00gImFyY2giKQorICAgIGVuZGlmKCkKKworICAgIGlmKE5PVCBDTUFLRV9DUk9TU0NPTVBJTElO
RyBBTkQgWEVWRV9OQVRJVkVfQlVJTEQpCisgICAgICBzZXQgKENNQUtFX0NfRkxBR1MgIiR7Q01B
S0VfQ19GTEFHU30gLW0ke09QVF9NfT1uYXRpdmUiKQorICAgIGVuZGlmKCkKKyAgICAKKyAgICBz
ZXQgKENNQUtFX0NfRkxBR1MgIiR7Q01BS0VfQ19GTEFHU30gJHtPUFRfREJHfSAtJHtPUFRfTFZ9
IC1mb21pdC1mcmFtZS1wb2ludGVyIC1XYWxsIC1Xbm8tdW51c2VkLWZ1bmN0aW9uIC1Xbm8tdW51
c2VkLXZhcmlhYmxlIC1Xbm8tYXR0cmlidXRlcyAtV25vLWVycm9yIC1Xbm8tc3RyaWN0LW92ZXJm
bG93IC1Xbm8tdW5rbm93bi1wcmFnbWFzICR7T1BUX1cwfSAtc3RkPWM5OSIpCisgICAgc2V0IChD
TUFLRV9DX0ZMQUdTICIke0NNQUtFX0NfRkxBR1N9IC1Xbm8tcG9pbnRlci1zaWduIC1wdGhyZWFk
IC1Xbm8tcG9pbnRlci10by1pbnQtY2FzdCAke09QVF9XMX0iKQogICAgIHNldCAoQ01BS0VfRVhF
X0xJTktFUl9GTEFHUyAiJHtDTUFLRV9FWEVfTElOS0VSX0ZMQUdTfSAtbG0iKQogZW5kaWYoKQog
Cg==
XB64_PATCH
# Filelist
# --------
# include/xeve/xeve.h
# include/xeve/xeve_exports.h
# lib/pkgconfig/xeve.pc
# lib/xeve/libxeve.a
# lib/libxeve.so
# bin/xeve_app
