#!/bin/bash
# ................................................
# setup util 1.0 2021-diasgc
# ................................................

# Target Triple
#   <arch><sub-arch>-<vendor>-<os>-<environ>
#       <arch>      aarch64, arm, i686, x86_64
#       <sub-arch>  v7a,v7m
#       <vendor>    apple, pc, ibm, unknown
#       <os>        darwin, linux, openbsd
#       <environ>   android, elf, gnu, gnueabihf
#
#

function check_install {
    local v0
    local v1
    for p in $@; do
        v0=$(dpkg-query -W $p 2>/dev/null | cut -f2)
        v1=$(apt-cache madison $p | cut -d '|' -f2 | head -n1 | xargs)
        if [ -z "${v0}" ];then
            printf "${CH}%-20s: ${C0}%s\n" "  $p" "installing..."
            printf "$(${apt_install} $p -y 2>/dev/null | grep $p | sed "s/^$p//" | head -n1)\n"
        elif [ "${v1}" == "${v0}" ]; then
            printf "${CH}%-20s: ${C0}%s\n" "  $p" "${v0}"
        else
            printf "${CH}%-20s: ${C0}%s" "  $p" "${v0} upgrading to..."
            printf "$(${apt_install} $p -y 2>/dev/null | grep $p | sed "s/^$p//" | head -n1)\n"
        fi  
    done
}

function update {
    while [ -n "${1}" ]; do
        case "${1}" in
            ndk|NDK)    install_ndk;;
            llvm-mingw) install_llvm_mingw;;
            llvm-gnu)   install_llvm_gnu;;
        esac
        shift
    done
}

function cmake_latest {
    sudo bash -c "$(wget -O - https://apt.kitware.com/kitware-archive.sh)"
}

function llvm_latest {
    sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
}

function libcheck {
    local v
    local g
    for fscript in *.sh; do
        case $fscript in _*|*build*|*setup*|*unpack*) continue;; esac
        v="$(./${fscript} --get var dev_vrs)"
        printf "${C0}%-20s:${CC0}%-10s" ${fscript} ${v}
        #if [ -n "${v}" ]; then
        g="$(./${fscript} --get vrs_remote 2>/dev/null)"
        printf "${CY0}%-10s\n" ${g}
        #fi
        #printf "\n"
    done
}

function select_ndk {
	echo -e "${CH}Android NDK Support:${C0}"
	PS3="Please select NDK version: "
	links=($(get_ndk_links))
	options=("None" $(echo "${links[@]}" | sed 's/https:\/\/dl\.google\.com\/android\/repository\/android-ndk-//g;s/-linux.zip//g'))
	select opt in "${options[@]}"
	do
		idx=$(($REPLY-2))
		if test $idx -ge 0; then
			p_install_ndk=true
			XB_HAS_NDK_CLANG=true
			export XB_NDK_URL="${links[$idx]}"
			echo -e "\e[1A${CH}Selected $(basename ${CC1}${XB_NDK_URL})\n${C0}"
			break;
		else
			p_install_ndk=false
			XB_HAS_NDK_CLANG=false
			echo -e "\e[1A${CH}None selected: do not install NDK${C0}\n"
			break;
		fi
	done
}

function pcount {
	
	printf "%-14s"
	local ln=0
	while read -r sln; do
		if [ -n "$sln" ]; then 
			((ln=ln+1))
			printf "\e[13D%-13s" "[${ln}/${XB_COUNT_MAX}]"
		fi
	done
	printf "\e[14D"
	
}

function get_ndk_links {
    echo "$(wget -qO- https://developer.android.com/ndk/downloads | grep -Po "https://dl.google.com/android/repository/android-ndk-r..*-linux.zip" | sed "/\"/d")"
}

function install_ndk {
	# No url, return
	test -z "${XB_NDK_URL}" && return 1

	local od=$(pwd)
	cd ${HOME}

    # install android-ndk
    test -z "$(command -v unzip)" && check_install unzip
	
    # Lets download
	if [ ! -f "tmp.zip" ]; then
		echo -ne "${CH}Downloading... ${C0} "
		tput sc #&& echo -ne "\e[$(tput lines);0H${CY1}"
		tput civis
		wget --progress=dot ${XB_NDK_URL} -O tmp.zip 2>&1 | grep --line-buffered "%" | sed -u -e "s,\.,,g" | awk '{printf("\r%4s %s eta:%s  ",$2,$1,$4)}'
		tput rc
	fi
	XB_COUNT_MAX=$(zipinfo -h tmp | tr '\n' ':' | awk -F':' '{print $5}' | xargs)
    echo -ne "${CH} decompressing... ${C0}"
    local fname=$(basename ${XB_NDK_URL})
    unzip tmp 2>&1 | pcount
	tput cnorm
    rm -f $fname tmp
    mv android-ndk-r* android-ndk
    export ANDROID_NDK_HOME="${HOME}/android-ndk"
    cd $od
}

function install_llvm_gnu {
    ${apt_install} llvm clang libc6-dev-arm64-cross libc6-dev-armhf-cross
}

function llvm_mingw_get_latest_version {
    echo $(curl --silent "https://api.github.com/repos/mstorsjo/llvm-mingw/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
}

function install_llvm_mingw {
    # install llvm-mingw
    local od=$(pwd)
    if [ -z "${LLVM_MINGW_HOME}" ]; then
        export LLVM_MINGW_HOME="$HOME/llvm-mingw"
    fi
    cd $(dirname ${LLVM_MINGW_HOME})
    [ -d "llvm-mingw" ] && rm -rf "llvm-mingw"
    export llvm_mingw_rel=$(llvm_mingw_get_latest_version)
    wget_untar "https://github.com/mstorsjo/llvm-mingw/releases/download/${llvm_mingw_rel}/llvm-mingw-${llvm_mingw_rel}-ucrt-ubuntu-20.04-x86_64.tar.xz" "llvm-mingw"    
    echo $llvm_mingw_rel >"${LLVM_MINGW_HOME}/version"
    export xv_llvm_mingw=$(./llvm-mingw/bin/aarch64-w64-mingw32-clang --version | grep -oP '\d*\.\d*.\d* (?=\()')
    cd $od
}

function build_utils {
    cd utils
    [ -n "$(command -v clang++)" ] && cc=clang++ || cc=g++
    printf "${CH}%-20s: ${C0}%s" "  lz-string" "compiling..."
    $cc -mtune=native -std=c++14 -O3 -Wall -stdlib=libstdc++ -c lz-string.cpp && clang++ -o lz-string lz-string.o && rm *.o && echo " done" || echo " fail"
    cd ..
}

function do_git_cleanup {
    echo -e "size before cleanup: $(du -s .git)\n"
    git filter-branch --index-filter 'git rm --cached --ignore-unmatch *.tar.gz' -- --all
    rm -Rf .git/refs/original
    rm -Rf .git/logs/
    git gc --aggressive --prune=now
    echo -e "\nDone\n\n"
    echo -e "size after cleanup: $(du -s .git)\n"
    exit 0
}

function check_slink {
    local status
	if [ ! -f "${1}" ]; then
		sudo ln -s "${2}" "${1}" 2>&1 >/dev/null && status="new" || status="${CR1}err${C0}"
        ${verbose} && printf "${CC1}%-6s ${C0}%-60s-> ${CW}%s\n" "    ${status}" "${1}" "${2}"
	elif [ "$(readlink ${1})" == "${2}" ]; then
        ${verbose} && printf "${CH}%-6s ${CD}%-60s-> ${C0}%s\n" "    ok" "${1}" "${2}"
    else
        sudo ln -s "${2}" "${1}" 2>&1 >/dev/null && status="${CY1}upd${C0}" || status="${CR1}err${C0}"
        ${verbose} && printf "${CC1}%-6s ${C0}%-60s-> ${CW}%s\n" "    ${status}" "${1}" "${2}"
    fi
    return 0
}

function check_wrapper_gnu {
    local overwrite=false
    case "${1}" in
        --overwrite) shift; overwrite=true;;
    esac
	if ${overwrite} || [ ! -f "/usr/${1}/bin/${2}" ]; then
		cat <<-eof | sudo tee /usr/${1}/bin/${2} >/dev/null
		#!/bin/bash
		${2} --target=${1} ${3} "\$@"
		eof
		sudo chmod +x "/usr/${1}/bin/${2}"
	fi
}

function check_wrapper_ndk {
    cat <<-eof | sudo tee ${3} >/dev/null
		#!/bin/bash
		\${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/${2}\${API:=${NDK_API_DEFAULT}}-${1} "\$@"
		eof
		sudo chmod +x ${3}
}

function do_update {
    while [ -n "${1}" ]; do
      case "${1}" in
        ndk|NDK)    install_ndk;;
        llvm-mingw) install_llvm_mingw;;
        llvm-gnu)   install_llvm_gnu;;
      esac
      shift
    done
    #exec ./x-setup
    exit 0
}

function xsetup_list {
    v=$1
    d=$2
    [ -n "$d" ] && d="'$d'"
    for f in *.sh; do
    v=$(grep "$1=$d" $f)
    [ -n "${v}" ] && echo "${f}: ${v}"
    done
    exit 0
}

function init_ndk {
    if	[ -z "${ANDROID_NDK_HOME}" ] || [ ! -d "${ANDROID_NDK_HOME}" ]; then
        ndk_clang_bin_dir=$(find ~ -name "aarch64-linux-android??-clang" | tail -n1)
        if [ -f "${ndk_clang_bin_dir}" ]; then
            export ANDROID_NDK_HOME=$(echo ${ndk_clang_bin_dir} | sed 's|/toolchains/llvm/prebuilt.*||')
        else
            select_ndk
	        [ -n "${XB_NDK_URL}" ] && install_ndk
        fi
        if [ -d "${ANDROID_NDK_HOME}" ]; then
            printf "\nexport ANDROID_NDK_HOME=${ANDROID_NDK_HOME}\n" >> ~/.bashrc && source ~/.bashrc
        fi
    fi
	if	[ -z "$(command -v clang)" ]; then
		read -p "Linux LLVM/Clang Support: Install LLVM/Clang Toolchain? [Y|n]: " p_install_llvm_gnu
        test "${p_install_llvm_gnu,,}" == "y" && p_install_llvm_gnu=true || p_install_llvm_gnu=false
        XB_HAS_GNU_CLANG=${p_install_llvm_gnu}
	fi
}


function check_ndk_symlink {
    [[ -z "$(readlink "$1" | grep ${ANDROID_NDK_HOME})" ]]
}

function update_ndkhome {
    sed -i 's@^export ANDROID_NDK_HOME=.*$@export ANDROID_NDK_HOME='"${ANDROID_NDK_HOME}"'@' ~/.bashrc
    source ~/.bashrc
}

# usage create_symlink <src> <dst> will test if src and dst exists first
function create_symlink {
    if [ ! -f "${2}" ] || [ ! "$(readlink ${2})" == "${1}" ]; then
        sudo ln -s "${1}" "${2}"
        ${verbose} && printf "${CC1}%-6s ${C0}%-60s-> ${CW}%s\n" "    new" "${1}" "${2}"
    else
        ${verbose} && printf "${CH}%-6s ${CD}%-60s-> ${C0}%s\n" "    ok" "${1}" "${2}"
    fi
}

function llvm_mingw_check_symlinks {
    local cl_abi

    if [ -z "$(ls -A ${LLVM_MINGW_HOME}/include)" ]; then
        rm -r "${LLVM_MINGW_HOME}/include"
        ln -s ${LLVM_MINGW_HOME}/generic-w64-mingw32/include ${LLVM_MINGW_HOME}/include
    fi

    for cl in aarch64 arm i686 x86_64; do

        target_dir="/usr/${cl}-w64-mingw32"
        cl_abi=${cl/arm/armv7}
        source_dir="${LLVM_MINGW_HOME}/${cl_abi}-w64-mingw32"
    
        test -d "${target_dir}"         || sudo mkdir -p "${target_dir}/bin"
        test -d "${target_dir}/dll"     || sudo ln -s "${source_dir}/bin"     "${target_dir}/dll"
        test -d "${target_dir}/include" || sudo ln -s "${source_dir}/include" "${target_dir}/include"
        test -d "${target_dir}/lib"     || sudo ln -s "${source_dir}/lib"     "${target_dir}/lib"
        test -d "${target_dir}/share"   || sudo ln -s "${source_dir}/share"   "${target_dir}/share"
        
        printf "   ${CH}Checking symlinks for ${CW}${cl_abi}\n"
        for e in addr2line ar as c++ clang clang++ dlltool g++ gcc ld llvm-ar llvm-ranlib nm objcopy objdump ranlib readelf size strings strip widl windres; do
    
            create_symlink "${LLVM_MINGW_HOME}/bin/${cl_abi}-w64-mingw32-${e}"    "${target_dir}/bin/${e}"
            create_symlink "${LLVM_MINGW_HOME}/bin/${cl_abi}-w64-mingw32uwp-${e}" "${target_dir}/bin/uwp-${e}"
    
        done
        
    done
    
    printf "${CH}%-20s: ${C0}%s\n" '  toolchain slinks' ok

}






# MAIN

clear

: "${dir_root:=$(dirname $0)}"
: "${NDK_API_DEFAULT:=34}"
#export LLVM_MINGW_JSON=$(curl -sL "https://api.github.com/repos/mstorsjo/llvm-mingw/releases/latest")
#llvm_mingw_targz=$(curl -sL "https://api.github.com/repos/mstorsjo/llvm-mingw/releases/latest" | jq -r -M '.assets[] | .browser_download_url' | grep '.*ucrt.*ubuntu.*'$(uname -p))

XB_HAS_NDK_CLANG=true
XB_HAS_GNU_CLANG=true
XB_HAS_MINGW_CLANG=true
XB_HAS_MINGW_GCC=false

# first-time load common functions
test -z ${vsh+x} && source .common

# set cyan theme color
CH=${CC0}
verbose=false
force=false
init=false
ts=false

p_install_ndk=false
p_install_ndk_symlinks=false
p_install_llvm_gnu=false
p_install_llvm_sysroot=false

splash
# load config
#[ -f ".config" ] && . .config || init=true
: "${apt_install:='apt install'}"
printf "\n${CH}%-20s: ${C0}%s\n" 'cmd install' "${apt_install}"
if [ -n "$(command -v sudo)" ]; then
  sudo echo -ne "Password: "
  echo
  apt_install="sudo ${apt_install}"
fi

# parse options
while [ "${1}" ]; do
case "${1}" in
  --verbose|-v)
    verbose=true
    ;;
  --force|-f)
    force=true
    ;;
  --git-cleanup)
    do_git_cleanup
    ;;
  --install)
    shift
    check_install $@
    exit 0
    ;;
  --latest-cmake)
    cmake_latest
    exit 0
    ;;
  --latest-llvm)
    llvm_latest
    exit 0
    ;;
  --update)
    shift
    do_update $@
    ;;
  --libcheck)
    libcheck
    exit 0
    ;;
  --list)
    shift
    xsetup_list $@
    ;;
  --build_utils)
    build_utils
    exit 0
    ;;
  --init)
    init=true
    ;;
esac
shift
done

${init} && init_ndk

echo -e "\n${CC1}This Machine:"
[ -z "${build_arch}" ] && build_arch="$(uname -m)-${OSTYPE,,}"
[ -z "${build_os}" ] && build_os=$(uname -s)
[ -z "${build_cpu}" ] && build_cpu=$(uname -m)
printf "${CH}%-20s: ${C0}%s\n" '  build arch' ${build_arch}
printf "${CH}%-20s: ${C0}%s\n" '  build os' ${build_os}
printf "${CH}%-20s: ${C0}%s\n" '  build cpu' ${build_cpu}

safe_mkdir ${dir_root}/builds/toolchain
export dir_toolchain="$(pwd)/builds/toolchain"

echo -e "\n${CC1}GNU-GCC:"
check_install gcc g++
# check for installed components
: "${XB_BUILD_GCC:=$(command -v gcc)}"
: "${XB_BUILD_GPP:=$(command -v g++)}"
test -z "${XB_BUILD_GCC}" && exit_err "Unable to install GCC. Aborting."
XB_GCC_VERSION=$(gcc -dumpversion)
printf "${CH}%-20s: ${C0}%s\n\n" "  gcc $(gcc -print-multiarch)" "version ${XB_GCC_VERSION}"

check_install 'gcc-aarch64-linux-gnu' 'g++-aarch64-linux-gnu' "libstdc++6-arm64-cross"
printf "${CH}%-20s: ${C0}%s\n\n" "  gcc $(aarch64-linux-gnu-gcc -print-multiarch)" "version $(aarch64-linux-gnu-gcc -dumpversion)"

check_install 'gcc-arm-linux-gnueabihf' 'g++-arm-linux-gnueabihf' 'libstdc++6-armhf-cross'
printf "${CH}%-20s: ${C0}%s\n\n" "  gcc $(arm-linux-gnueabihf-gcc -print-multiarch)" "version $(arm-linux-gnueabihf-gcc -dumpversion)"

check_install 'gcc-i686-linux-gnu' 'g++-i686-linux-gnu'
printf "${CH}%-20s: ${C0}%s\n\n" "  gcc $(i686-linux-gnu-gcc -print-multiarch)" "version $(i686-linux-gnu-gcc -dumpversion)"

XB_GCC_TOP_VER=$(apt search gcc 2>/dev/null | grep -oP 'gcc-[0-9\.]+' | sed 's,gcc-,,' | sort -n |tail -n1)
if [ "${XB_GCC_VERSION}" != "${XB_GCC_TOP_VER}" ]; then
  printf "${CH}%-20s: ${CY1}%s${C0}\n\n" "  gcc version ${XB_GCC_TOP_VER} is available." "Run 'xsetup --update gcc' to update"
fi

echo -e "\n${CC1}LLVM-Clang:"

echo
cclang=$(command -v clang)

if [ -z "${cclang}" ]; then
    PS3='LLVM not installed: '
    select o in 'Do not install' 'Install latest OS package' 'Install devel from llvm.org'; do
      case ${REPLY} in
        2) check_install clang-format clang-tidy clang-tools clang clangd libc++-dev \
                         libc++1 libc++abi-dev libc++abi1 libclang-dev libclang1 \
                         liblldb-dev libllvm-ocaml-dev libomp-dev libomp5 lld lldb \
                         llvm-dev llvm-runtime llvm python3-clang
                         ;;
        3) sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)";;
      esac
    done
fi

if [ -n "${cclang}" ]; then
    printf "${CH}%-20s: ${C0}%s\n" "  found at" ${cclang}
    CLANG_GNU_VERSION_FULL=$(clang -dumpversion)
    CLANG_GNU_VERSION=${CLANG_GNU_VERSION_FULL%%\.*}
    printf "${CH}%-20s: ${C0}%s\n" '  clang' "${CLANG_GNU_VERSION_FULL}"
    # install symlinks
    check_install libllvmlibc-${CLANG_GNU_VERSION}-dev
	cl=(aarch64 arm i686 x86_64)
	ab=(arm64 armhf i386 x86_64)
	abi=(gnu gnueabihf gnu gnu)
    cclang_args=''
	for a in 0 1 2 3; do
        t="${cl[$a]}-linux-${abi[$a]}"
        if [ "${t}" != "${build_arch}" ]; then
            check_install libc6-dev-${ab[$a]}-cross libstdc++6-${ab[$a]}-cross
            [ -d "/usr/${t}/bin" ] || sudo mkdir -p "/usr/${t}/bin"
            for e in ar as nm addr2line objcopy objdump ranlib readelf size strings strip windres; do
                check_slink "/usr/${t}/bin/llvm-${e}" "/usr/bin/llvm-${e}"
			done
            llvm_vrs=$(ls -lh ${cclang} | grep -oP 'llvm-\d+')
            if [ -n "${llvm_vrs}" ]; then
                #check_slink "/usr/bin/llvm-addr2line" "/usr/lib/${llvm_vrs}/bin/llvm-addr2line"
                check_slink "/usr/bin/llvm-windres" "/usr/lib/${llvm_vrs}/bin/llvm-windres"
            fi
			check_slink "/usr/${t}/bin/ld.lld" "/usr/bin/ld.lld"
            test "${ab[${a}]}" = "armhf" && cclang_args='-mfloat-abi=hard -mfpu=neon' || cclang_args='' 
			check_wrapper_gnu --overwrite "${t}" 'clang' "${cclang_args}"
			check_wrapper_gnu --overwrite "${t}" 'clang++' "${cclang_args}"
		fi
	done
fi


if [ "${OSTYPE}" != "linux-android" ] && $XB_HAS_NDK_CLANG; then
    echo -e "\n${CC1}Android NDK:"
    if [ -z "${ANDROID_NDK_HOME}" ]; then
        ndk_clang_bin_dir=$(find ~ -name "aarch64-linux-android??-clang" | tail -n1)
        if [ -z "${ndk_clang_bin_dir}" ]; then
            install_ndk
        else
            export ANDROID_NDK_HOME=$(echo ${ndk_clang_bin_dir} | sed 's|/toolchains/llvm/prebuilt.*||')
        fi
        if [ -n "${ANDROID_NDK_HOME}" ]; then
            printf "\nexport ANDROID_NDK_HOME=${ANDROID_NDK_HOME}\n" >> ~/.bashrc && source ~/.bashrc
        fi
    fi
    if [ -n "${ANDROID_NDK_HOME}" ]; then
        r="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android"
        ANDROID_NDK_API="$(find ${r} -maxdepth 1 -type d | sed 's,'${r}',,' | sort | tail -n1 | sed 's,/,,')"
        printf "${CH}%-20s: ${C0}%s\n" "  found at" ${ANDROID_NDK_HOME}
        printf "${CH}%-20s: ${C0}%s\n" "  API level" ${ANDROID_NDK_API}
        ndk_release=$(cat ${ANDROID_NDK_HOME}/source.properties | grep -Po '\.Revision.=.\K([0-9\.\-a-zA-Z]+)')
        NDK_RELEASE=$(cat ${ANDROID_NDK_HOME}/source.properties | grep -Po 'BaseRevision.=.\K([0-9\.]+)')
        printf "${CH}%-20s: ${C0}%s " '  version' ${ndk_release}
        ndk_release_list=($(wget -qO- https://developer.android.com/ndk/downloads | grep -oP '(?<=ndkVersion..)\d+\.\d+\.\d+.*(?=")'))
        ndk_release_latest="${ndk_release_list[-1]}"
        if [ "${ndk_release}" = "${ndk_release_latest}" ]; then
            echo -e "(updated)"
        else
            echo -e "${CY1} latest is ${ndk_release_latest}${C0}"
            ndk_parent="$(dirname ${ANDROID_NDK_HOME})"
            if [ -d "${ndk_parent}/${ndk_release_latest}" ]; then
                read -p "  Switch from ${ndk_version} to ${ndk_release_latest}? [Y|n]" yn;
                case $yn in
                    y*|Y*)
                        export ANDROID_NDK_HOME="${ndk_parent}/${ndk_release_latest}"
                        vrs_ndk=${ndk_release_latest}
                        sed -i 's@^export ANDROID_NDK_HOME=.*$@export ANDROID_NDK_HOME='"${ANDROID_NDK_HOME}"'@' ~/.bashrc
                        source ~/.bashrc
                        ;;
                esac
            fi
        fi
        ndk_build="linux-$(uname -m)"
        TOOLCHAIN_NDK="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/${ndk_build}"
        SYSROOT_NDK="${TOOLCHAIN_NDK}/sysroot"
        CLANG_NDK_VERSION_FULL="$(${TOOLCHAIN_NDK}/bin/clang -dumpversion)"
        CLANG_NDK_VERSION="${CLANG_NDK_VERSION_FULL%%\.*}"

        ndk_sysroot="${TOOLCHAIN_NDK}/sysroot"
        #ndk_clang_version=$(${TOOLCHAIN_NDK}/bin/clang -dumpversion)
        printf "${CH}%-20s: ${C0}%s\n" '  clang' "${CLANG_NDK_VERSION_FULL}"

        # check and create symlinks in toolchains dir if needed
        c_arch=('aarch64' 'arm' 'i686' 'x86_64')
        c_abi=('arm64-v8a' 'armeabi-v7a' 'x86' 'x86_64')
        c_clang=('aarch64-linux-android' 'armv7a-linux-androideabi' 'i686-linux-android' 'x86_64-linux-android')
        c_lib=('aarch64-linux-android' 'arm-linux-androideabi' 'i686-linux-android' 'x86_64-linux-android')

        
        for i in 0 1 2 3; do
            #cl="${c_arch[${i}]}"

            printf "   ${CH}Checking symlinks for ${CW}${c_arch[${i}]}"
            dir_toolchain="/usr/${c_lib[${i}]}"
            #
            [ -d "${dir_toolchain}/bin" ] || sudo mkdir -p "${dir_toolchain}/bin"
            ${verbose} && echo -ne "\n     ${CD}clang"
            if ${force} || [ ! -f "${dir_toolchain}/bin/clang" ]; then
                check_wrapper_ndk "clang" "${c_clang[${i}]}" "${dir_toolchain}/bin/clang"
            fi
            ${verbose} && printf " clang++"
            if ${force} || [ ! -f "${dir_toolchain}/bin/clang++" ]; then 
                check_wrapper_ndk "clang++" "${c_clang[${i}]}" "${dir_toolchain}/bin/clang++"
            fi
            #[ -f "${dir_toolchain}/bin/as" ] || sudo ln -s "${TOOLCHAIN_NDK}/bin/${c_lib[${i}]}-as" "${dir_toolchain}/bin/as"
            #[ -f "${dir_toolchain}/bin/ld" ] || sudo ln -s -f "${TOOLCHAIN_NDK}/bin/lld" "${dir_toolchain}/bin/ld"
            check_ndk_symlink "${dir_toolchain}/bin/ld" && sudo ln -sfn "${TOOLCHAIN_NDK}/bin/ld" "${dir_toolchain}/bin/ld"
            ${verbose} && printf " ld"
            check_ndk_symlink "${dir_toolchain}/bin/yasm" && sudo ln -sfn "${TOOLCHAIN_NDK}/bin/yasm" "${dir_toolchain}/bin/yasm"
            ${verbose} && printf " yasm"
            
            for j in as ar nm addr2line objcopy objdump ranlib readelf readobj size strings strip; do
                check_ndk_symlink "${dir_toolchain}/bin/${j}" && sudo ln -sfn "${TOOLCHAIN_NDK}/bin/llvm-${j}" "${dir_toolchain}/bin/${j}"
                ${verbose} && printf " $j"
            done
            
            check_ndk_symlink "${dir_toolchain}/lib" && sudo ln -sfn "${TOOLCHAIN_NDK}/sysroot/usr/lib/${c_lib[${i}]}" "${dir_toolchain}/lib"
            [ -f "${dir_toolchain}/lib/libpthread.a" ] || sudo ${dir_toolchain}/bin/ar cr "${dir_toolchain}/lib/libpthread.a"
            [ -f "${dir_toolchain}/lib/librt.a" ] || sudo ${dir_toolchain}/bin/ar cr "${dir_toolchain}/lib/librt.a"
            
            check_ndk_symlink "${dir_toolchain}/sysroot" && sudo ln -sfn "${SYSROOT_NDK}" "${dir_toolchain}/sysroot"
            check_ndk_symlink "${dir_toolchain}/include" && sudo ln -sfn "${SYSROOT_NDK}/usr/include" "${dir_toolchain}/include"
            
            [ -d "${dir_root}/builds/android/${c_abi[${i}]}" ] || mkdir -p "${dir_root}/builds/android/${c_abi[${i}]}"
            
            [ -d "${dir_toolchain}/local" ] && sudo unlink ${dir_toolchain}/local
            sudo ln -sf "${dir_root}/builds/android/${c_abi[${i}]}" "${dir_toolchain}/local"
            echo -e "${CH} ok${C0}"
        done
        printf "${CH}%-20s: ${C0}%s\n" '  toolchain symlinks' ok
        
        [ -f "${dir_toolchain}/include/sys/soundcard.h" ] || printf "#include <linux/soundcard.h>" >"${dir_toolchain}/include/sys/soundcard.h"
    else
        echo -e "  not installed"
    fi
fi

echo -e "\n${CC1}LLVM MINGW:"
if [ -z "${LLVM_MINGW_HOME}" ]; then
    llvm_mingw_bin_dir=$(find ~ -name "aarch64-w64-mingw32uwp-dlltool" | head -n1)
    if [ -z "${llvm_mingw_bin_dir}" ]; then
        echo -ne "  not found. Install? "; read -p "[Y|n]" pndk
        case $pndk in y|Y) install_llvm_mingw;; esac
    else
        export LLVM_MINGW_HOME=$(dirname $(dirname $llvm_mingw_bin_dir))
    fi
fi 

if [ -n "${LLVM_MINGW_HOME}" ]; then
    printf "${CH}%-20s: ${C0}%s\n" "  found at" ${LLVM_MINGW_HOME}
    
    llvm_mingw_latest_release=$(llvm_mingw_get_latest_version)
    [ -f "${LLVM_MINGW_HOME}/version" ] || echo "$llvm_mingw_latest_release" >>"${LLVM_MINGW_HOME}/version"
    LLVM_MINGW_REL=$(cat ${LLVM_MINGW_HOME}/version)
    printf "${CH}%-20s: ${C0}%s " '  release' ${LLVM_MINGW_REL}
    if [ "${LLVM_MINGW_REL}" == "${llvm_mingw_latest_release}" ]; then
        echo -e "(updated)"
    else
        echo -e "${CY1} latest is ${llvm_mingw_latest_release}${C0}"
    fi

    CLANG_MINGW_VERSION_FULL=$(${LLVM_MINGW_HOME}/bin/clang -dumpversion)
    CLANG_MINGW_VERSION=${llvm_mingw_clang_version%%\.*}
    printf "${CH}%-20s: ${C0}%s\n" '  clang' "${CLANG_MINGW_VERSION_FULL}"

    
    # check and create symlinks in toolchains dir if needed
    llvm_mingw_check_symlinks
fi

echo -e "\n${CC1}${b} Build tools${C0}"
check_install build-essential make pkg-config
echo -e "\n${CC1}${b} Assembly compilers${C0}"
check_install nasm yasm
echo -e "\n${CC1}${b} Cmake${C0}"
check_install cmake cmake-curses-gui
echo -e "\n${CC1}${b} Meson${C0}"
check_install meson ninja-build
echo -e "\n${CC1}${b} Autotools${C0}"
check_install automake autoconf autogen autopoint libtool-bin m4

echo -e "\n${CC1}${b} Repository tools${C0}"
check_install git subversion mercurial lzip unzip

echo -e "\n${CC1}${b} Other tools${C0}"
check_install curl gperf bison texinfo patch jq gettext

#echo -e "\n${CC1}${b} Utilities${C0}"
#if [ ! -f "${dir_root}/utils/lz-string" ]; then
#    build_utils
#Sfi

echo -ne "\n${CC1}${b} Writing config${C0}"

if [ -z "${llvm_mingw}" ] && [ -n "${LLVM_MINGW_HOME}" ]; then
    llvm_mingw=${LLVM_MINGW_HOME}
fi

case "$(uname -s)" in
    Linux)
      build_arch=$(echo $(uname -m)-linux-gnu)
      [ -n "$(grep -q BCM2708 /proc/cpuinfo)" ] && build_arch="${build_arch}eabihf"    
      if [ -n "$(command -v getprop)" ]; then
        build_arch=$(echo $(uname -m)-linux-android)
        export API=$(getprop ro.build.version.sdk)
      fi
      ;;
    Darwin)
      build_arch=$(echo $(uname -m)-darwin-gnu)
      ;;
    CYGWIN*|MINGW32*|MSYS*|MINGW*)
      build_arch=$(echo $(uname -m)-w64-mingw32)
      ;;
esac

#xv_x64_mingw=$(ls -t /usr/lib/gcc/x86_64-w64-mingw32 | grep -E "*-win32" | head -n1 2>/dev/null )
#xv_x86_mingw=$(ls -t /usr/lib/gcc/i686-w64-mingw32 | grep -E "*-win32" | head -n1 2>/dev/null)

: "${API:=34}"

cat <<-EOF >${dir_root}/.config
#!/bin/bash
export config_lastupdate=$(date +%s) \\
    dir_root="$(pwd)" \\
    sudo=$(command -v sudo) \\
    apt_install="${apt_install}" \\
    build_arch="${build_arch}" \\
    XB_HAS_GNU_CLANG=${XB_HAS_GNU_CLANG} \\
    XB_HAS_MINGW_CLANG=${XB_HAS_MINGW_CLANG} \\
    XB_HAS_MINGW_GCC=${XB_HAS_MINGW_GCC} \\
    XB_HAS_NDK_CLANG=${XB_HAS_NDK_CLANG} \\
    CLANG_NDK_VERSION=${CLANG_NDK_VERSION} \\
    CLANG_GNU_VERSION=${CLANG_GNU_VERSION} \\
    CLANG_MINGW_VERSION=${CLANG_MINGW_VERSION} \\
    LLVM_MINGW_HOME="${llvm_mingw}" \\
    ANDROID_NDK_HOME="${ANDROID_NDK_HOME}" \\
    ANDROID_NDK_API="${ANDROID_NDK_API}" \\
    NDK_RELEASE="${NDK_RELEASE}" \\
    TOOLCHAIN_NDK="${TOOLCHAIN_NDK}" \\
    SYSROOT_NDK="${SYSROOT_NDK}" \\
    LLVM_MINGW_REL="${LLVM_MINGW_REL}" \\
    MAKE_EXECUTABLE="$(command -v make)" \\
    CMAKE_EXECUTABLE="$(command -v cmake)" \\
    NASM_EXECUTABLE="$(command -v nasm)" \\
    PKG_CONFIG="$(command -v pkg-config)" \\
    HOST_NPROC="$(nproc)" \\
    xv_llvm_mingw="${xv_llvm_mingw}" \\
    llvm_mingw_rel="${llvm_mingw_rel}" \\
    GCC_AARCH64_REL="$(/usr/bin/aarch64-linux-gnu-gcc -dumpversion)" \\
    GCC_ARMHF_REL="$(/usr/bin/arm-linux-gnueabihf-gcc -dumpversion)" \\
    GCC_I686_REL="$(/usr/bin/i686-linux-gnu-gcc -dumpversion)" \\
    GCC_X86_64_REL="$(/usr/bin/x86_64-linux-gnu-gcc -dumpversion)" \\
    xv_x64_mingw="${xv_llvm_mingw}" \\
    xv_x86_mingw="${xv_llvm_mingw}"
EOF

echo -ne "... ${CC1}Done!${C0}\n\n"














# unused
function llvm_mingw_check_symlinks_old {
    # check and create symlinks in toolchains dir if needed
    for cl in aarch64 arm i686 x86_64; do
        for e in ar nm addr2line dlltool objcopy ranlib readelf strings strip windres; do
            v="${dir_toolchain}/${cl}-w64-mingw32-${e}"
            [ ! -f "${v}" ] && ln -s "${LLVM_MINGW_HOME}/bin/llvm-${e}" "${v}" 2>/dev/null
        done
        for e in as c++ c11 c99 cc clang clang++ g++ gcc; do
            v="${dir_toolchain}/${cl}-w64-mingw32-${e}"
            [ ! -f "${v}" ] && ln -s "${LLVM_MINGW_HOME}/bin/clang-target-wrapper.sh" "${v}" 2>/dev/null
        done
        [ ! -f "${dir_toolchain}/${cl}-w64-mingw32-objdump" ] && ln -s "${LLVM_MINGW_HOME}/bin/objdump-wrapper.sh" "${dir_toolchain}/${cl}-w64-mingw32-objdump" 2>/dev/null
        [ ! -f "${dir_toolchain}/${cl}-w64-mingw32-ld" ] && ln -s "${LLVM_MINGW_HOME}/bin/ld-wrapper.sh" "${dir_toolchain}/${cl}-w64-mingw32-ld" 2>/dev/null
        [ ! -f "${dir_toolchain}/${cl}-w64-mingw32-widl" ] && ln -s "${LLVM_MINGW_HOME}/bin/i686-w64-mingw32-widl" "${dir_toolchain}/${cl}-w64-mingw32-ld" 2>/dev/null
    done
    printf "${CH}%-20s: ${C0}%s\n" '  toolchain slinks' ok
}