#!/bin/bash
# ................................................
# setup util 2.0 2024 diasgc
# ................................................

: "${dir_root:=$(dirname $0)}"
# first-time load common functions
[ -z ${vsh+x} ] && source .common

test "$TERM_PROGRAM" == "vscode" && \
  printf "\n${CR1}This won't run on VSCODE terminal.\nExiting.\n\n${C0}" && \
  exit 0

clear

GNU_GCC=$(command -v gcc)
test -n "${GNU_GCC}" && GNU_GCC_VERSION="$(gcc -dumpversion)"

GNU_CLANG=$(command -v clang)
test -n "${GNU_CLANG}" && \
  GNU_CLANG_VERSION_FULL="$(clang -dumpversion)" && \
  GNU_CLANG_VERSION=${GNU_CLANG_VERSION_FULL%%\.*}

ARCH_NATIVE="$(uname -m)"
SYS_NATIVE="$(uname -s)"