#!/bin/bash

source .utils

for a in ../*.sh; do

    src=$(cat $a | grep -oP "src='.*'" | sed "s/src=//g;s/'//g")

    if [ -n "$src" ]; then
        case $src in
            *git*) printf "%-20s: %-20s\n" "  $a" "git: $src";;
            *svn*) printf "%-20s: %-20s\n" "  $a" "svn: $src";;
        esac
    fi
    
done