#!/bin/bash

lib='celt'
dsc='CELT is a low-delay audio codec'
lic='BSD-2c'
spdx_id='BSD-2-Clause'
src='https://gitlab.xiph.org/xiph/celt.git'
cfg='ag'
dep='ogg'

dev_bra='master'
dev_vrs='0.11.4'
pkg_deb=''
eta='60'
     
lst_inc='celt/*.h'
lst_lib='libcelt0'
lst_bin=''
lst_lic='LICENSE AUTHORS'
lst_pc='celt.pc'

am_config="--enable-experimental-postfilter \
     --enable-float-approx \
     --enable-fixed-point \
     --enable-custom-modes"

source_patch(){
  sed -i 's|XIPH_PATH_OGG|#XIPH_PATH_OGG|g' configure
}



# cpu av8 av7 x86 x64
# NDK ++  ++  ++  ++  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc

# Filelist
# --------
# include/celt/celt_header.h
# include/celt/celt_types.h
# include/celt/celt.h
# lib/pkgconfig/celt.pc
# lib/libcelt0.so
# lib/libcelt0.a
# lib/libcelt0.la
