#!/bin/bash

lib='dwarfs'
dsc='A fast high compression read-only file system for Linux, Windows and macOS'
lic='GNU General Public License v3.0'
src="https://github.com/mhx/dwarfs"
sub='submodule update --init'
src_rel=false

cfg='cmake'

dev_bra='master'
dev_vrs=''
pkg_deb=''
eta='0'

lst_inc=''
lst_lib=''
lst_bin=''
lst_lic='LICENSE AUTHORS'
lst_pc=''

# cpu av8 av7 x86 x64
# NDK  .   .   .   .  clang
# GNU  .   .   .   .  clang/gcc
# WIN  .   .   .   .  clang/gcc
