#!/bin/bash
# cpu av8 av7 x86 x64
# NDK N/A N/A  .   .  clang
# GNU N/A N/A  .   .  gcc
# WIN N/A N/A  .   .  clang/gcc

lib='ffevc'
dsc='ffmpeg supporting EVC codec and file formats'
lic='BSD-2c'
src='https://github.com/mpeg5/ffevc.git'
cfg='cmake'

dev_vrs=''

