#!/bin/bash

lib='flac'
dsc='Free Lossless Audio Codec'
lic='BSD'
src='https://github.com/xiph/flac.git'
dep='ogg libiconv'

cfg='cmake'
cmake_config='-DBUILD_CXXLIBS=ON -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DINSTALL_MANPAGES=OFF -DWITH_ASM=ON -DWITH_OGG=ON'
cmake_bin='BUILD_PROGRAMS'
cmake_static='BUILD_STATIC_LIBS'

lst_inc='FLAC++/*.h FLAC/*.h'
lst_lib='libFLAC libFLAC++'
lst_bin='flac metaflac'
lst_lic='COPYING.FDL COPYING.GPL COPYING.LGPL COPYING.Xiph AUTHORS'
lst_pc='flac.pc flac++.pc'


dev_bra='main'
dev_vrs='1.4.3'
pkg_deb="libflac-dev"
eta='60'



# cpu av8 av7 x86 x64
# NDK +++ +++ +++ +++ clang
# GNU +++ +++  .   .  gcc
# WIN  .   .   .   .  clang/gcc


# Filelist
# --------
#
# share/doc/flac/AUTHORS
# share/doc/flac/COPYING.Xiph
# share/doc/flac/COPYING.LGPL
# share/doc/flac/COPYING.GPL
# share/doc/flac/COPYING.FDL
# bin/metaflac
# bin/flac
# lib/pkgconfig/flac++.pc
# lib/libFLAC++.a
# lib/libFLAC++.so
# lib/pkgconfig/flac.pc
# lib/libFLAC.a
# lib/libFLAC.so
# include/FLAC++/metadata.h
# include/FLAC++/export.h
# include/FLAC++/encoder.h
# include/FLAC++/decoder.h
# include/FLAC++/all.h
# include/FLAC/stream_encoder.h
# include/FLAC/stream_decoder.h
# include/FLAC/ordinals.h
# include/FLAC/metadata.h
# include/FLAC/format.h
# include/FLAC/export.h
# include/FLAC/callback.h
# include/FLAC/assert.h
# include/FLAC/all.h
# share/FLAC/cmake/flac-config-version.cmake
# share/FLAC/cmake/flac-config.cmake
# share/FLAC/cmake/targets-release.cmake
# share/FLAC/cmake/targets.cmake
# 
