#!/bin/bash
# cpu av8 av7 x86 x64
# NDK  .   .   .   .  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc

lib='gnulib'
dsc='GNU Portability Library'
lic=''
vrs=''
src='https://git.savannah.gnu.org/git/gnulib.git'
url='https://www.gnu.org/software/gnulib/'
cfg='ar'


dev_bra='master'
dev_vrs=''
pkg_deb='gnulib'
eta='0'

lst_inc=''
lst_lib=''
lst_bin=''
lst_lic='LICENSE AUTHORS'
lst_pc=''

