#!/bin/bash

lib='hashpp'
dsc='Portable C++ hashing library'
lic='Zlib'
url='https://create.stephan-brumme.com/hash-library/'
src='https://github.com/stbrumme/hash-library.git'
cfg='cmake'

build_strip=false
patch='hashpp-01'

lst_inc='
 hashpp/crc32.h
 hashpp/hash.h
 hashpp/hmac.h
 hashpp/keccak.h
 hashpp/md5.h
 hashpp/sha1.h
 hashpp/sha256.h
 hashpp/sha3.h'
lst_lib='libhashpp'
lst_bin=''
lst_lic='LICENSE readme.md'
lst_pc='hashpp.pc'

dev_vrs='9'
pkg_deb=''
eta='60'




# cpu av8 av7 x86 x64
# NDK +++ +++  .   .  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc


# Filelist
# --------
#
# include/hashpp/crc32.h
# include/hashpp/hash.h
# include/hashpp/hmac.h
# include/hashpp/keccak.h
# include/hashpp/md5.h
# include/hashpp/sha1.h
# include/hashpp/sha256.h
# include/hashpp/sha3.h
# lib/libhashpp.a
# lib/libhashpp.so
# lib/pkgconfig/hashpp.pc
# share/doc/hashpp/LICENSE
# share/doc/hashpp/readme.md
