#!/bin/bash

lib='lepton'
dsc='Lepton is a tool and file format for losslessly compressing JPEGs by an average of 22%.'
lic='Apache License 2.0'
src="https://github.com/dropbox/lepton"

cfg='cmake'
on_config_arm(){
    cmake_config+=' -DSSE_VECTORIZATION=OFF'
}

dev_bra='master'
dev_vrs=''
pkg_deb=''
eta='0'

lst_inc=''
lst_lib=''
lst_bin=''
lst_lic='LICENSE AUTHORS'
lst_pc=''

# cpu av8 av7 x86 x64
# NDK  .   .   .   .  clang
# GNU  .   .   .   .  clang/gcc
# WIN  .   .   .   .  clang/gcc
