#!/bin/bash

lib='lib7zip'
dsc='c++ library wrapper of 7zip'
lic='MLP-2.0'
src='https://github.com/stonewell/lib7zip.git'
patch='lib7zip-01'

cfg='cmake'
cmake_config+='-DENABLE_TEST=OFF'

dev_vrs='3.0.0'
pkg_deb=''
eta='1095'

source_config(){
    git submodule init && git submodule update
}



# cmake incomplete - no install

# cpu av8 av7 x86 x64
# NDK  .   .   .   .  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc
