#!/bin/bash

# cpu av8 av7 x86 x64
# NDK ++   .   .   .  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc

lib='libfishsound'
pkg='fishsound'
dsc='Simple API that wraps Xiph.Org audio codecs'
lic='BSD-2c'
spdx_id='BSD-2-Clause'
src='https://gitlab.xiph.org/xiph/libfishsound.git'
dep='ogg vorbis speex flac sndfile liboggz'

cfg='ag'
CPPFLAGS='-Wno-unused-parameter -Wno-incompatible-function-pointer-types'

dev_bra='master'
dev_vrs=''
eta='20'
pkg_deb='libfishsound1-dev'

# ld.lld: error: undefined symbol: oggpack_***


# Filelist
# --------
# include/fishsound/fishsound.h
# include/fishsound/decode.h
# include/fishsound/comments.h
# include/fishsound/deprecated.h
# include/fishsound/constants.h
# include/fishsound/encode.h
# lib/pkgconfig/fishsound.pc
# lib/libfishsound.la
# lib/libfishsound.so
# lib/libfishsound.a
