#!/bin/bash

lib='libiconv'
dsc='Character set conversion library'
lic='LGPL2.1'
src='https://git.savannah.gnu.org/git/libiconv.git'
url='https://www.gnu.org/software/libiconv'

cfg='ac'
am_config=" --enable-extra-encodings"
ac_reconf=false

lst_inc='iconv.h libcharset.h localcharset.h'
lst_lib='libiconv libcharset'
lst_bin='iconv'
lst_lic='COPYING COPYING.LIB AUTHORS'
lst_pc='libiconv.pc'

dev_vrs='1.17'
pkg_deb=''
eta='90'

on_config(){
	vrs="$(curl https://ftp.gnu.org/gnu/libiconv/ 2>/dev/null | grep -oP 'libiconv-[0-9\.]+.tar.gz' | tail -n 1 | grep -oP '[0-9]+.[0-9]+')"
	src="https://ftp.gnu.org/gnu/libiconv/libiconv-${vrs}.tar.gz"
}

on_create_pc(){
	build_pkgconfig --url=${url} --libs=-liconv
}



# cpu av8 av7 x86 x64
# NDK +++ +++ +++ +++ CLANG
# GNU  +   +   +   +  GCC
# WIN +++ +++  +   +  CLANG/GCC

# Filelist
# --------
# include/iconv.h
# include/libcharset.h
# include/localcharset.h
# lib/libcharset.so
# lib/pkgconfig/libiconv.pc
# lib/libiconv.so
# lib/libcharset.a
# lib/libcharset.la
# lib/libiconv.a
# lib/libiconv.la
# share/doc/libiconv/COPYING.LIB
# share/doc/libiconv/AUTHORS
# share/doc/libiconv/COPYING
# bin/iconv