#!/bin/bash

lib='libmysofa'
pkg_deb="${lib}-dev"
dsc='Reader for AES SOFA files to get better HRTFs'
lic='BSD'
src='https://github.com/hoene/libmysofa.git'
cfg='cmake'
pkg='libmysofa'
eta='60'

cmake_config="-DBUILD_TESTS=OFF"
cmake_static='BUILD_STATIC_LIBS'

dev_bra='master'
dev_vrs='1.3'

lst_inc='mysofa.h'
lst_lib='libmysofa'
lst_bin=''
lst_lic='LICENSE'
lst_pc='libmysofa.pc'



# cpu av8 av7 x86 x64
# NDK ++   .   .   .  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc

# Filelist
# --------
# include/mysofa.h
# lib/pkgconfig/libmysofa.pc
# lib/libmysofa.so
# lib/libmysofa.a
# share/libmysofa/MIT_KEMAR_normal_pinna.sofa
# share/doc/libmysofa/LICENSE
