#!/bin/bash
# cpu av8 av7 x86 x64
# NDK  .   .   .   .  clang
# GNU  .   .   .   .  clang/gcc
# WIN  .   .   .   .  clang/gcc

lib='libtdb'
pkg='tdb'
dsc='Trivial Database'
lic='GLP-2.0'
url='https://tdb.samba.org/'
src_rel=true

cfg='other'
cfg_cmd='./configure'

dev_bra='main'
dev_vrs='1.4.10'
pkg_deb='libtdb-dev'
eta='688'

libtdb_cross(){
	ANDROID_NDK_API=33 # set < 34 because NDK API 34 introduces function with different args len
	cfg_cmd+=" --cross-compile --cross-answers cross-answers.txt --host=${arch} "
	cat <<-EOF >"${dir_src}/cross-answers.txt"
		Checking uname sysname type: "${PLATFORM}"
		Checking uname machine type: "${arch}"
		Checking uname release type: "dontcare"
		Checking uname version type: "dontcare"
		Checking simple C program: "hello world"
		rpath library support: OK
		-Wl,--version-script support: NO
		Checking getconf LFS_CFLAGS: NO
		Checking for large file support without additional flags: OK
		Checking for -D_FILE_OFFSET_BITS=64: OK
		Checking for -D_LARGE_FILES: OK
		Checking correct behavior of strtoll: NO
		Checking for working strptime: NO
		Checking for C99 vsnprintf: OK
		Checking for HAVE_SHARED_MMAP: OK
		Checking for HAVE_MREMAP: OK
		Checking for HAVE_INCOHERENT_MMAP: NO
		Checking for HAVE_SECURE_MKSTEMP: OK
		EOF
}

on_config(){
	# support for shared libs only
	build_static=false
	build_shared=true

	vrs="$(curl -sL https://www.samba.org/ftp/tdb/ | grep -oP 'tdb-[0-9\.]+.tar.gz' | tail -n1)"
	src="https://www.samba.org/ftp/tdb/${vrs}"
	vrs="$(sed 's,tdb-,,;s,.tar.gz,,' <<<${vrs})"
	cfg_cmd+=" --prefix=${dir_install} --disable-python" # --without-ad-dc"
	${host_cross} && libtdb_cross
}

lst_inc=''
lst_lib=''
lst_bin=''
lst_lic='COPYING AUTHORS'
lst_pc=''

