#!/bin/bash
# cpu av8 av7 x86 x64
# NDK  .   .   .   .  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc

lib='libxft'
dsc='FreeType-based font drawing library for X'
lic='MIT'
src='https://gitlab.freedesktop.org/xorg/lib/libxft.git'
dep='fontconfig freetype libx11 libxext libxrender'

cfg='ag'

dev_bra='master'
dev_vrs='2.3.8'
pkg_deb='libxft-dev'
eta='0'

lst_inc=''
lst_lib=''
lst_bin=''

