#!/bin/bash
# cpu av8 av7 x86 x64
# NDK  .   .   .   .  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc

lib='libx11'
dsc='Core X11 protocol client library'
lic='Other'
src='https://gitlab.freedesktop.org/xorg/lib/libx11.git'
dep='xorg-macros libxtrans xorgproto'

cfg='ac'

dev_bra='main'
dev_vrs='1.8.9'
pkg_deb='libx11-dev'
eta='0'

lst_inc=''
lst_lib=''
lst_bin=''
lst_lic='LICENSE AUTHORS'
lst_pc=''

on_src_release(){
    vrs=$(curl -sL https://www.x.org/releases/individual/lib/ | grep -oP 'libX11-\d+.\d+.\d+.tar.gz' | tail -n1)
    src="https://www.x.org/releases/individual/lib/${vrs}"
    vrs="$(sed 's,libX11-,,;s,.tar.gz,,' <<<${vrs})"
}

on_config(){
    ${src_rel} && on_src_release
}

