#!/bin/bash

lib='mimalloc'
dsc='mimalloc is a compact general purpose allocator with excellent performance.'
lic='MIT'
src='https://github.com/microsoft/mimalloc.git'

cfg='cmake'
cmake_shared='MI_BUILD_SHARED'
cmake_static='MI_BUILD_STATIC'

dev_bra='dev'
dev_vrs='1.7.5'
pkg_deb='libmimalloc-dev'
eta='64'

on_create_pc(){
    build_pkgconfig --libs=-lmimalloc
}

lst_inc='mimalloc-1.7/mimalloc-new-delete.h
    mimalloc-1.7/mimalloc-override.h
    mimalloc-1.7/mimalloc.h'
lst_lib='libmimalloc.so mimalloc-1.7/libmimalloc.a'
lst_bin=''
lst_lic='LICENSE'
lst_pc='libmimalloc.pc'



# cpu av8 av7 x86 x64
# NDK ++  ++   .   .  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc

# Filelist
# --------
#
# include/mimalloc-1.7/mimalloc-new-delete.h
# include/mimalloc-1.7/mimalloc-override.h
# include/mimalloc-1.7/mimalloc.h
# share/doc/mimalloc/LICENSE
# lib/libmimalloc.so
# lib/pkgconfig/libmimalloc.pc
# lib/mimalloc-1.7/mimalloc.o
# lib/mimalloc-1.7/libmimalloc.a
# lib/cmake/mimalloc-1.7/mimalloc-release.cmake
# lib/cmake/mimalloc-1.7/mimalloc.cmake
# lib/cmake/mimalloc-1.7/mimalloc-config-version.cmake
# lib/cmake/mimalloc-1.7/mimalloc-config.cmake
# lib/cmake/mimalloc-1.7/mimalloc-release.cmake
# lib/cmake/mimalloc-1.7/mimalloc.cmake
