#!/bin/bash

lib='pcre'
pkg='libpcre'
dsc=''
lic='BSD-3c'
src='https://sourceforge.net/projects/pcre/files/pcre/8.45/pcre-8.45.tar.gz'
patch="pcre-01"
dep='bzip2 readline editline'

cfg='cmake'

dev_bra=''
dev_vrs='8.45'
pkg_deb=''
eta='0'

lst_inc='pcre.h pcreposix.h pcrecpparg.h pcre_scanner.h pcre_stringpiece.h pcrecpp.h'
lst_lib='libpcreposix libpcrecpp libpcre'
lst_bin='pcre_scanner_unittest pcrecpp_unittest pcregrep pcre-config pcretest pcre_stringpiece_unittest'



# cpu av8 av7 x86 x64
# NDK  .   .   .   .  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc

# Filelist
# --------
# include/pcre.h
# include/pcreposix.h
# include/pcrecpparg.h
# include/pcre_scanner.h
# include/pcre_stringpiece.h
# include/pcrecpp.h
# lib/pkgconfig/libpcreposix.pc
# lib/pkgconfig/libpcre.pc
# lib/pkgconfig/libpcrecpp.pc
# lib/libpcreposix.a
# lib/libpcrecpp.a
# lib/libpcre.a
# bin/pcre_scanner_unittest
# bin/pcrecpp_unittest
# bin/pcregrep
# bin/pcre-config
# bin/pcretest
# bin/pcre_stringpiece_unittest
