#!/bin/bash
# cpu av8 av7 x86 x64
# NDK  .   .   .   .  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc

lib='perl'
dsc='Perl'
lic=''
cfg='ac'

cross_vrs='1.1.3'

dev_bra='master'
dev_vrs=''
pkg_deb=''
eta='0'

lst_inc=''
lst_lib=''
lst_bin=''
lst_lic='LICENSE AUTHORS'
lst_pc=''

eta='20'

source_patch(){
    vrs_cross="$(tar_version 'https://github.com/arsv/perl-cross/releases' 'perl-cross-')"
    src_cross="https://github.com/arsv/perl-cross/archive/refs/tags/${vrs_cross}.tar.gz"
    pushdir ${dir_sources}
    curl_tar_simple "${src_cross}" -xz
    sed -i 's,^cnf\/configure \"\$\@\",\$\{dir_src\}\/&,' ${dir_src}/configure
    popdir
}

on_config(){
    vrs="$(tar_version 'https://www.cpan.org/src/5.0/' 'perl-')"
    src="http://www.cpan.org/src/5.0/perl-${vrs}.tar.gz"
    #if ${host_cross}; then
    #    cfg='ac'
    #    unset lib_link
    #    am_config="--target=${arch} -Duseshrplib"
    #fi
}

build_config(){
    args=( "--target=${arch}" "--prefix=${dir_install}" "--sysroot=${SYSROOT}" ) # "-Duseshrplib"
    ../configure "${args[@]}"
    # ndk issue: undefine HAS_FUTIMES in config.h
    $host_ndk && sed -i 's,^#define HAS_FUTIMES.*,,' config.h
}

