#!/bin/bash

lib='qpdf'
pkg='libqpdf'
dsc='Primary QPDF source code and documentation'
lic='Apache-2.0'
src='https://github.com/qpdf/qpdf.git'
dep='gnutls libjpeg zlib'

cfg='cmake'
cmake_static='BUILD_STATIC_LIBS'
cmake_config='-DBUILD_DOC=OFF -DUSE_IMPLICIT_CRYPTO=OFF -DDEFAULT_CRYPTO=OpenSSL -DINSTALL_EXAMPLES=OFF -DMAINTAINER_MODE=ON'

dev_bra='master'
dev_vrs='11.9.1'
pkg_deb='libqpdf-dev'
eta='1008'

lst_inc=''
lst_lib=''
lst_bin=''
lst_lic='LICENSE.txt'
lst_pc=''



# cpu av8 av7 x86 x64
# NDK  F  .   .   .  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc

# fail to install