#!/bin/bash
# cpu av8 av7 x86 x64
# NDK  +   .   .   .  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc

lib='rav1e'
dsc='The fastest and safest AV1 encoder. '
lic='BSD-2c'
src="https://github.com/xiph/rav1e.git"

cfg='cargo'

dev_bra='master'
dev_vrs='0.7.1'
pkg_deb='librav1e-dev'
eta='592'

on_config(){
    build_dir=$dir_src
    cargo_config+=" --target ${arch}"
}

lst_inc=''
lst_lib=''
lst_bin=''
lst_lic='LICENSE AUTHORS'
lst_pc=''

