#!/bin/bash
# cpu av8 av7 x86 x64
# NDK ++  ++  ++  ++  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc

lib='soxr'
apt='libsoxr-dev'
dsc='The SoX resampler library'
lic='LGPL-2.1'
src='https://git.code.sf.net/p/soxr/code' sty='git'
cfg='cmake'
eta='45'
cbk='DBUILD_EXAMPLES'
CFG='-DBUILD_TESTS=OFF'
lst_inc='soxr.h soxr-lsr.h'
lst_lib='libsoxr.a libsoxr-lsr.a'
lst_bin=''
lst_lic='share/doc/libsoxr/LICENCE'

. xbuilder.sh

start

<<'XB64_PATCH'
LS0tIHNyYy9DTWFrZUxpc3RzLm9sZAkyMDIxLTEwLTEyIDE3OjUyOjUwLjMxOTAwMDAwMCArMDEw
MAorKysgc3JjL0NNYWtlTGlzdHMudHh0CTIwMjEtMTAtMTIgMTg6MDc6NDIuNDUzMTI4MTAwICsw
MTAwCkBAIC04NCw2ICs4NCwxMiBAQAogICBJTlNUQUxMX05BTUVfRElSICR7TElCX0lOU1RBTExf
RElSfQogICBMSU5LX0lOVEVSRkFDRV9MSUJSQVJJRVMgIiIKICAgUFVCTElDX0hFQURFUiAiJHtQ
Uk9KRUNUX05BTUV9LmgiKQoraWYoQlVJTERfU0hBUkVEX0xJQlMgQU5EIEJVSUxEX1NUQVRJQ19M
SUJTKQorICBzZXQoUFJPSkVDVF9OQU1FX1NUQVRJQyAke1BST0pFQ1RfTkFNRX0tc3RhdGljKQor
ICBhZGRfbGlicmFyeSAoJHtQUk9KRUNUX05BTUVfU1RBVElDfSBTVEFUSUMgJHtTT1VSQ0VTfSkK
KyAgdGFyZ2V0X2xpbmtfbGlicmFyaWVzICgke1BST0pFQ1RfTkFNRV9TVEFUSUN9IFBSSVZBVEUg
JHtMSUJTfSAke0xJQk1fTElCUkFSSUVTfSkKKyAgc2V0X3RhcmdldF9wcm9wZXJ0aWVzICgke1BS
T0pFQ1RfTkFNRV9TVEFUSUN9IFBST1BFUlRJRVMgT1VUUFVUX05BTUUgJHtQUk9KRUNUX05BTUV9
KQorZW5kaWYoKQogaWYgKEJVSUxEX0ZSQU1FV09SSykKICAgc2V0X3RhcmdldF9wcm9wZXJ0aWVz
ICgke1BST0pFQ1RfTkFNRX0gUFJPUEVSVElFUyBGUkFNRVdPUksgVFJVRSkKIGVsc2VpZiAoTk9U
IFdJTjMyKQpAQCAtMTE1LDEzICsxMjEsMTkgQEAKICAgICBjb25maWd1cmVfZmlsZSAoJHtDTUFL
RV9DVVJSRU5UX1NPVVJDRV9ESVJ9LyR7TFNSfS5wYy5pbiAke0NNQUtFX0NVUlJFTlRfQklOQVJZ
X0RJUn0vJHtMU1J9LnBjKQogICAgIGluc3RhbGwgKEZJTEVTICR7Q01BS0VfQ1VSUkVOVF9CSU5B
UllfRElSfS8ke0xTUn0ucGMgREVTVElOQVRJT04gJHtMSUJfSU5TVEFMTF9ESVJ9L3BrZ2NvbmZp
ZykKICAgZW5kaWYgKCkKKyAgaWYoQlVJTERfU0hBUkVEX0xJQlMgQU5EIEJVSUxEX1NUQVRJQ19M
SUJTKQorICAgIHNldChMU1JfU1RBVElDICR7TFNSfV9zdGF0aWMpCisgICAgYWRkX2xpYnJhcnkg
KCR7TFNSX1NUQVRJQ30gU1RBVElDICR7TFNSfSkKKyAgICB0YXJnZXRfbGlua19saWJyYXJpZXMg
KCR7TFNSX1NUQVRJQ30gJHtQUk9KRUNUX05BTUVfU1RBVElDfSkKKyAgICBzZXRfdGFyZ2V0X3By
b3BlcnRpZXMgKCR7TFNSX1NUQVRJQ30gUFJPUEVSVElFUyBPVVRQVVRfTkFNRSAke0xTUn0pCisg
IGVuZGlmKCkKIGVuZGlmICgpCiAKIAogCiAjIEluc3RhbGxhdGlvbiAoZnJvbSBidWlsZCBmcm9t
IHNvdXJjZSk6CiAKLWluc3RhbGwgKFRBUkdFVFMgJHtQUk9KRUNUX05BTUV9ICR7TFNSfQoraW5z
dGFsbCAoVEFSR0VUUyAke1BST0pFQ1RfTkFNRX0gJHtQUk9KRUNUX05BTUVfU1RBVElDfSAke0xT
Un0gJHtMU1JfU1RBVElDfQogICBGUkFNRVdPUksgREVTVElOQVRJT04gJHtGUkFNRVdPUktfSU5T
VEFMTF9ESVJ9CiAgIExJQlJBUlkgREVTVElOQVRJT04gJHtMSUJfSU5TVEFMTF9ESVJ9CiAgIFJV
TlRJTUUgREVTVElOQVRJT04gJHtCSU5fSU5TVEFMTF9ESVJ9Cg==
XB64_PATCH

# Filelist
# --------
# include/soxr-lsr.h
# include/soxr.h
# lib/libsoxr-lsr.a
# lib/pkgconfig/soxr.pc
# lib/pkgconfig/soxr-lsr.pc
# lib/libsoxr.a
# lib/libsoxr-lsr.so
# lib/libsoxr.so
# share/doc/libsoxr/NEWS
# share/doc/libsoxr/LICENCE
# share/doc/libsoxr/README
