#!/bin/bash

lib='speex'
dsc='Speex is an audio codec tuned for speech'
lic='BSD'
src='https://gitlab.xiph.org/xiph/speex.git'
dep='speexdsp'

cfg='meson'
meson_config='-Dtest-binaries=disabled'
meson_bin='tools'

on_build_bin(){
    dep+=' ogg'
}

dev_vrs='1.2.1'
pkg_deb='libspeex-dev'
eta='80'

lst_inc='speex/*.h'
lst_lib='libspeex'
lst_bin='speexdec speexenc'
lst_lic='COPYING AUTHORS'
lst_pc='speex.pc'

#LDFLAGS+=" -lm"

# cpu av8 av7 x86 x64
# NDK +++  .   .   .  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc

# Filelist
# --------
# include/speex/speex_header.h
# include/speex/speex_callbacks.h
# include/speex/speex.h
# include/speex/speex_bits.h
# include/speex/speex_stereo.h
# include/speex/speex_config_types.h
# include/speex/speex_types.h
# lib/pkgconfig/speex.pc
# lib/libspeex.a
# lib/libspeex.la
# lib/libspeex.so
# share/man/man1/speexenc.1
# share/man/man1/speexdec.1
# share/doc/speex/manual.pdf
# share/doc/speex/AUTHORS
# share/doc/speex/COPYING
# share/aclocal/speex.m4
# bin/speexdec
# bin/speexenc
