#!/bin/bash
# cpu av8 av7 x86 x64
# NDK  .   .   .   .  clang
# GNU  .   .   .   +  clang/gcc
# WIN  .   .   .   +  clang/gcc

lib='svt-vp9'
pkg='SvtVp9Enc'
dsc='SVT VP9 encoder'
lic='Other'
src="https://github.com/OpenVisualCloud/SVT-VP9"
src_rel=false

cfg='cmake'
cmake_definitions=( -Wno-unused-function -Wno-unused-but-set-variable -Wno-unused-but-set-parameter -Wno-unused-parameter )

on_config_arm(){
    exit_err "Unsupported for arm processors"
}
on_config_ndk(){
    # unsupported pthread_setaffinity_np on ndk
    exit_err "Unsupported for Android"
}

dev_bra='master'
dev_vrs='0.3.0'
pkg_deb=''
eta='15'

lst_inc=''
lst_lib=''
lst_bin=''
lst_lic='LICENSE AUTHORS'
lst_pc=''

eta='20'
