#!/bin/bash
# cpu av8 av7 x86 x64
# NDK  .   .   .   .  clang
# GNU  .   .   .   .  gcc
# WIN  .   .   .   .  clang/gcc

lib='zenity'
dsc='Zenity'
lic='LGPL2.1'
vrs=''
src="https://gitlab.gnome.org/GNOME/zenity"
dep='libadwaita-1-dev libwebkitgtk-6.0-dev gettext help2man itstool desktop-file-utils libglib2.0-dev-bin'

cfg='meson'

dev_bra='master'
dev_vrs='3.44.4'
pkg_deb='zenity'
eta='0'

lst_inc=''
lst_lib=''
lst_bin=''
lst_lic='LICENSE AUTHORS'
lst_pc=''

eta='20'

on_config(){
    $host_cross && exit_err "Cross compiling unavailable"
}

