#!/bin/bash

lib='zfp'
dsc='Compressed numerical arrays that support high-speed random access'
lic='BSD-3c'
src='https://github.com/LLNL/zfp.git'
url='http://oldhome.schmorp.de/marc/liblzf.html'

cfg='cmake'
cmake_config="-DBUILD_TESTING=OFF -DBUILD_GMOCK=OFF"

on_create_pc(){
    vrs="$(c_printf 'include/zfp' 'version.h' '"%s",ZFP_VERSION_STRING')"
    build_pkgconfig --libs=-llzf
}

dev_bra='master'
dev_vrs='1.0.1'
pkg_deb='libzfp-dev'
eta='112'

lst_inc='zfp.hpp zfp.h zfp/array.h
zfp/factory.hpp zfp/index.hpp zfp/bitstream.h
zfp/array.hpp zfp/array1.hpp zfp/array2.hpp zfp/array3.hpp zfp/array4.hpp
zfp/constarray1.hpp zfp/constarray2.hpp zfp/constarray3.hpp zfp/constarray4.hpp 
zfp/bitstream.inl zfp/codec/gencodec.hpp zfp/codec/zfpcodec.hpp zfp/version.h
zfp/internal/codec/genheader.hpp zfp/internal/codec/zfpheader.hpp
zfp/internal/zfp/system.h zfp/internal/zfp/types.h
zfp/internal/zfp/macros.h zfp/internal/zfp/inline.h
zfp/internal/array/store4.hpp zfp/internal/array/view3.hpp
zfp/internal/array/iterator3.hpp zfp/internal/array/handle2.hpp
zfp/internal/array/pointer2.hpp zfp/internal/array/reference1.hpp
zfp/internal/array/view4.hpp zfp/internal/array/pointer1.hpp
zfp/internal/array/cache2.hpp zfp/internal/array/cache1.hpp
zfp/internal/array/reference3.hpp zfp/internal/array/exception.hpp
zfp/internal/array/pointer4.hpp zfp/internal/array/pointer3.hpp
zfp/internal/array/cache3.hpp zfp/internal/array/handle1.hpp
zfp/internal/array/iterator1.hpp zfp/internal/array/memory.hpp
zfp/internal/array/iterator2.hpp zfp/internal/array/store2.hpp
zfp/internal/array/cache4.hpp zfp/internal/array/store1.hpp
zfp/internal/array/reference2.hpp zfp/internal/array/store3.hpp
zfp/internal/array/iterator4.hpp zfp/internal/array/reference4.hpp
zfp/internal/array/cache.hpp zfp/internal/array/view1.hpp
zfp/internal/array/store.hpp zfp/internal/array/handle4.hpp
zfp/internal/array/view2.hpp zfp/internal/array/header.hpp
zfp/internal/array/traits.hpp zfp/internal/array/handle3.hpp'
lst_lib='libzfp'
lst_bin='zfp'
lst_lic='LICENSE'
lst_pc='zfp.pc'

# Filelist
# --------
# include/zfpcarray3.h
# include/zfparray.h
# include/zfpcarray2.h
# include/zfparray2.h
# include/zfpcarray1.h
# include/bitstream.h
# include/zfparray1.h
# include/zfp/exception.h
# include/zfp/genheader.h
# include/zfp/pointer2.h
# include/zfp/view2.h
# include/zfp/handle2.h
# include/zfp/view3.h
# include/zfp/cache.h
# include/zfp/store3.h
# include/zfp/iterator1.h
# include/zfp/cache4.h
# include/zfp/iterator2.h
# include/zfp/memory.h
# include/zfp/cache2.h
# include/zfp/view4.h
# include/zfp/zfpheader.h
# include/zfp/types.h
# include/zfp/store2.h
# include/zfp/traits.h
# include/zfp/handle4.h
# include/zfp/reference1.h
# include/zfp/store1.h
# include/zfp/store.h
# include/zfp/pointer4.h
# include/zfp/iterator4.h
# include/zfp/handle3.h
# include/zfp/reference4.h
# include/zfp/cache1.h
# include/zfp/version.h
# include/zfp/pointer1.h
# include/zfp/cache3.h
# include/zfp/pointer3.h
# include/zfp/reference2.h
# include/zfp/view1.h
# include/zfp/reference3.h
# include/zfp/store4.h
# include/zfp/header.h
# include/zfp/macros.h
# include/zfp/iterator3.h
# include/zfp/handle1.h
# include/zfp/system.h
# include/zfpcpp.h
# include/zfpcarray4.h
# include/zfpindex.h
# include/zfparray3.h
# include/zfpcodec.h
# include/zfparray4.h
# include/zfpfactory.h
# include/zfp.h
# include/gencodec.h
# lib/pkgconfig/zfp.pc
# lib/cmake/zfp/zfp-targets-release.cmake
# lib/cmake/zfp/zfp-targets.cmake
# lib/cmake/zfp/zfp-config-version.cmake
# lib/cmake/zfp/zfp-config.cmake
# lib/libzfp.so
# share/doc/zfp/LICENSE
# bin/zfp
